### ISSUE TITLE
Hostile mobs removed immediately on spawn

### ISSUE THREAD

**Issue by silvasky54** [miniaturepets/issues#145]
*Short Description:* Pets based on hostile mobs are removed immediately upon spawning

*Long Description:* Pets based on hostile mobs are removed immediately upon spawning. All other pets work as normal. I have edited the worldguard config and even removed both worldguard and bentobox to see if anything changes but with no luck.

*Instructions for Re-Producing The Bug:* Install spigot 1.15.2, install plugins listed in dump file, upload default and vanilla pet packs, attempt to spawn ghast/creeper etc

*Dump File Link:* https://pastebin.com/a35n7bgW

**Comment by Amokinio** [comment]
Hello, something is preventing pets from spawning, it's not necesserily WorldGuard, it could be anything. It's mostly lobby admin plugins.

Check for those.

**Comment by silvasky54** [comment]
Hey, thanks for the reply.

I've removed all plugins except Mpet and still having the same issue.

Here's the dump file https://pastebin.com/CtNLBNij

**Comment by Amokinio** [comment]
Hi, please paste the output of running `/ver` on your server here.

**Comment by silvasky54** [comment]
25.02 23:44:07 [Server] Server thread/INFO This server is running CraftBukkit version git-Spigot-8faa8b4-3d61a85 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
25.02 23:44:07 [Server] Server thread/INFO You are running the latest version

**Comment by Amokinio** [comment]
Hello again, I've just tried again to install MPets on a fresh server using the same Spigot build as you use and everything works smoothly. You've modified something in server configuration that prevents pets from spawning. Check for modifications in server.properties, things like spawn NPCS and stuff like that.

**Comment by Amokinio** [comment]
Issue closed due to lack of response.

**Comment by silvasky54** [comment]
Sorry I've been ill but I've done some testing. I've come to the conclusion that pets based on hostile mobs won't spawn in void worlds but others will. All mobs spawn in a normal world on the same server. 

Is this something you could fix or add support for?

**Comment by Amokinio** [comment]
Pets based on hostiles won't be able to spawn in worlds they cannot spawn as regular hostiles simply because it's a restriction set by Minecraft. A way around would be to create a chicken based pet that is built like the hostile in question.

**Comment by silvasky54** [comment]
Regular hostile mobs still spawn as normal though on the islands. It's just the hostile pets that don't.

How would I modify the pets base anyway? I'm using the default and vanilla pack.

**Comment by ZrochStudios** [comment]
![image](https://user-images.githubusercontent.com/62026397/76333057-76d66f00-62c7-11ea-94f0-34c92f4a02c6.png)
On a skyblock island when I /mpet and selected any hostile mobs it quickly removed it, is it due to void generating a world from bentobox or maybe another variable in play and if so could it be fixed? Or does skyblock worlds have to redesigned hostile mobs using armorstands or a passive mob to function?

**Comment by liorsl** [comment]
Are you able to spawn hostile mobs in any other way?

**Comment by silvasky54** [comment]
Yes, they spawn naturally and I can spawn them with eggs and the /spawnmob command

**Comment by liorsl** [comment]
Can you spawn pets outside of skyblock islands?

**Comment by silvasky54** [comment]
> Can you spawn pets outside of skyblock islands?

Yes. I have a normal world on the same server that the hostile pets spawn on. It's just in void worlds that they don't.

**Comment by liorsl** [comment]
It sounds like an error outside of our plugin. Can you try deleting the plugin that makes the void world?

**Comment by Alontrle** [comment]
Can you also double check and make sure those worlds aren't in Peaceful, and if they are, try setting them to another difficulty. Could be an issue there

**Comment by danielnaaman** [comment]
@silvasky54 This is pending your response, please respond within 48 hours or this issue will be closed.

**Comment by danielnaaman** [comment]
Will be opened on my behalf shortly.
