### ISSUE TITLE
Pet as Hat keeps falling down!

### ISSUE THREAD

**Issue by TheAncientBook** [MiniaturePets/Issues#157]
*Short Description: When having a pet on as a Hat, the Hat keeps falling down, and goes above the head again, and so it repeats. This occurs in version: (1.8.x)* 

*Long Description: NONE* 

*Instructions for Re-Producing The Bug: Simply take a pet on as a hat, and it keeps falling down, going above the player head again, falls down again... etc.* 

*Dump File Link: 
![Honeycam_2020-02-28_01-06-16](https://user-images.githubusercontent.com/61551799/75606415-c7daac00-5aec-11ea-9d73-85eb917c7ff1.gif)
*

**Comment by Amokinio** [comment]
Approved

**Comment by liorsl** [comment]
Hello,
Can you provide us with a dump?

**Comment by TheAncientBook** [comment]
> Hello,
> Can you provide us with a dump?

Here is your pastebin dump https://pastebin.com/gVR8Nktc

**Comment by liorsl** [comment]
We could not reproduce that bug, pet hat is working as expected. Could you try it with another pet?

**Comment by TheAncientBook** [comment]
It happens with every single pet @liorsl

**Comment by liorsl** [comment]
Try to remove each plugin in your server until the problem is solved, as the issue is not with MiniaturePets, as per my testing I could not reproduce it.

**Comment by danielnaaman** [comment]
Do as Voigon said, can't reproduce myself.

Closed.
