### ISSUE TITLE
can't ride pet, it just teleports to the player

### ISSUE THREAD

**Issue by crispyklown81** [miniaturepets/issues#165]
Hi, when trying to ride the pet it just teleports the pet to the player but says the player is riding the pet. There are no errors in the console, it does the same thing when using the command or the gui.
I didn't have this issue until the latest release.
server version is 1.13.2 paper
Mpet Dump: https://pastebin.com/3bmn0zNH

**Comment by Golicraft** [comment]
Hey. I have the exact same issues

**Comment by liorsl** [comment]
Can you upload a video or a gif with the issue? I can't understand the problem

**Comment by crispyklown81** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47828989/78612963-95814480-7838-11ea-869e-e8c49a33eb0b.gif)

**Comment by liorsl** [comment]
Can you try enabling debug mode and checking if there is a error in console?

**Comment by crispyklown81** [comment]
I enabled debug mode and tried to ride the pet, there's no errors or anything, it only happens with the latest release, all other versions before works just fine.

**Comment by danielnaaman** [comment]
@crispyklown81 Please downgrade, we'll be working on a fix when releasing version `v2.4.0`.

Thanks,
Daniel.

**Comment by danielnaaman** [comment]
This should be fixed on the next release.
