### ISSUE TITLE
Miniaturepets Crash upon riding/punching mobs

### ISSUE THREAD

**Issue by hellominers-ultra** [miniaturepets/issues#169]
*Short Description:* 
When punching a mob causes kick to hub server, this also occurs on right click. Potentially an issue with riding. I'm sorry wish I could provide more info.

*Instructions for Re-Producing The Bug:* 
**Punch mob**
You are more than welcome to come on my server and test contact me beforehand to arrange. I can send any files or logs requested.

*Dump File Link:*
http://prntscr.com/rueziq

**Comment by danielnaaman** [comment]
Thanks for being as informative as you can, I've assigned your issue to the development team. Please wait patiently.

**Comment by liorsl** [comment]
Can you enable debug mode and send us the log from when this happens?

**Comment by NacOJerk** [comment]
Hey also please provide a /mpet dump file.

**Comment by hellominers-ultra** [comment]
https://pastebin.com/SUCc6crD Here is your dump file

http://prntscr.com/s3ewy7 Error when right clicking mob

**Comment by hellominers-ultra** [comment]
https://pastebin.com/SUCc6crD Here is your dump file

http://prntscr.com/s3ewy7 Error when right clicking mob

**Comment by danielnaaman** [comment]
Hi, your Miniature Pets version is entirely out-of-date. We don't provide support for such outdated version. Please upgrade to **v2.3.8**. Don't upgrade to **v2.3.9**.

Let me know when it's done and if the error still occurs.

**Comment by danielnaaman** [comment]
This was closed due to lack of user interaction.
