### ISSUE TITLE
Pets not removed when switching worlds

### ISSUE THREAD

**Issue by N0tMyFaultOG** [MiniaturePets/Issues#170]
*Description:* 
Pets are not removed when switching worlds. I see the following message when switching worlds
![](https://i.imgur.com/pbKfeZP.png)
but if I return to the other world again, the pet keeps staying there
![](https://i.imgur.com/kaweIHx.png)
The left pet should have been removed when switching worlds but it keeps staying, the right pet has been summoned again with the pet gui.

*Instructions for Re-Producing The Bug:* 
Setup a 1.12.2 Paper server and switch the worlds while having a pet equipped.

*Dump File Link:*
https://pastebin.com/tnPiu2Es

**Comment by Ollieed** [comment]
Hi all,

I just had some help from Amokinio on our server with the exact same issue, also on a Paper Spigot 1.12.2 server. It still doesn't seem to be working, but I'll add the error here that was shown when switching worlds to give you some help.

http://prntscr.com/rvoqv5

Also our /mpet dump:

https://pastebin.com/UWhvBtZR

**Comment by Ollieed** [comment]
One other thing: I also can't ride any of my pets, Amokinio also tested this out on my server, and should know more about the issue.

**Comment by danielnaaman** [comment]
@N0tMyFaultOG @Ollieed Problem was resolved in will be available in the next release. (2.4.0)
