### ISSUE TITLE
Region Guard x Miniature Pets Bug

### ISSUE THREAD

**Issue by BboyZeroOne** [miniaturepets/issues#175]
Region Guard x Miniature Pets Bug

### Technical Information
* Server Software: PaperSpigot 1.15.2
* Plugin Version:  v2.3.9
* Dump File: https://pastebin.com/bryZWRKQ
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
1. Players are unable to spawn their pets in any region other than global.
2. Players who ride their pets could enter restricted regions that they are denied access from.

**Instructions To Produce**
1. /mpet and select a pet.
2. Ride your pet.
3. Enter any region that you are denied access from. (Region flag: entry-deny)

**Logs**
[latest.log](https://github.com/miniaturepets/issues/files/4500558/latest.log)

**Visual Demonstration**
None, issue speaks for itself.

**Free Speech**
I've talked to world guard dev and asked if anything could be done, this is his response.

"worldguard literally can't cancel events that don't happen
bukkit throws movement events for normal "player riding a vehicle" stuff
if we get playermove/vehiclemove events, we can cancel them"

WorldGuard Discord: https://discord.gg/sXRbMPb

**Comment by BboyZeroOne** [comment]
Alright, I will downgrade and test it out.

I'll test and see if the older version fixes both of these issues.

**Comment by danielnaaman** [comment]
Great. Please keep me up-to-date.

**Comment by BboyZeroOne** [comment]
Issue still persist even after downgrading.

**Comment by liorsl** [comment]
Hello,
Please try to create a region without a flag.

**Comment by BboyZeroOne** [comment]
> Hello,
> Please try to create a region only with default settings.

Do you mean, without any flags?

**Comment by danielnaaman** [comment]
> > Hello,
> > Please try to create a region only with default settings.
> 
> Do you mean, without any flags?

Yes, just the default ones.

It is very possible there's a flag disrupting it.

**Comment by BboyZeroOne** [comment]
If its a region without any flags, they can spawn their pets normally.

If there is only 1 (entry-deny) flag, players can still ride their pet there.

**Comment by liorsl** [comment]
In worldguard config, please set block-plugin-spawning to false.

**Comment by BboyZeroOne** [comment]
Okay, let me try that. If I set it to false, what do you want me to test?

Spawning pets in region or entering a restricted region while riding on pets?

**Comment by danielnaaman** [comment]
Set it to false, and then try to use the plugin. @BboyZeroOne

**Comment by BboyZeroOne** [comment]
Ok I set it to false, spawning pets in region works for now. But the riding pets into restricted regions still exist.

**Comment by danielnaaman** [comment]
Did you try it with the new version as well?

**Comment by BboyZeroOne** [comment]
Yes, I tried it with the latest version.

**Comment by danielnaaman** [comment]
@liorsl

**Comment by liorsl** [comment]
Hello,
What is your definition of restricted region?

**Comment by BboyZeroOne** [comment]
Regions with this enabled.

(Region flag: entry-deny)

**Comment by liorsl** [comment]
We do not support entry denial yet.
