### ISSUE TITLE
Miniature Pets Vanish Bug

### ISSUE THREAD

**Issue by BboyZeroOne** [miniaturepets/issues#176]
Miniature Pets Vanish Bug

### Technical Information
* Server Software: PaperSpigot 1.15.2
* Plugin Version:  v2.3.9
* Dump File: https://pastebin.com/bryZWRKQ

### General Information

**Bug Description**
Players are able to "vanish" themselves when disguised as a pet.

**Instructions To Produce**
Scenario 1:
1. '/mpet' and select a pet.
2. Click on your pet and disguise as your pet.
3. Your name should be hidden from both tab list and '/list'.
4. Players are unable to '/tpa' nor 'tp' to a disguised pet player.

Scenario 2:
1. '/mpet' and select a pet.
2. Click on your pet and disguise as your pet.
3. Enter a restricted region guard area. You will be bugged out in vanish and won't be able to unvanish yourself with '/mpet' menu if you tried to remove/resummon your pet. You will be permanently be in vanish during the whole session.
4. Leave the server/session to fix the vanish disguise bug.

**Logs**
[latest.log](https://github.com/miniaturepets/issues/files/4500599/latest.log)

**Visual Demonstration**
Disguised player named BrownSugarBBT, with his pet chicken.
https://imgur.com/a/vuHzJqj

**Free Speech**
I have done this test multiple times and it works. Scenario 2 involves with world guard. A lot of players abuse this bug to prevent staffs from teleporting to them.

WorldGuard Discord: https://discord.gg/sXRbMPb

**Comment by danielnaaman** [comment]
Hi, can you try setting `hideDisguisedPlayers` to `false`?

Thanks.

**Comment by BboyZeroOne** [comment]
I set this to false. This is what player sees. 

https://imgur.com/a/A9Bz48y

But they are not in vanish in either tablist or /list

**Comment by BboyZeroOne** [comment]
Players can still enter restricted zone if the region has only "entry: false"

**Comment by liorsl** [comment]
This issue will be solved on the next release.
