### ISSUE TITLE
Use mythicmobs to generate monsters, heights above 117 will not be able to spawn again

### ISSUE THREAD

**Issue by dezps** [miniaturepets/issues#178]
# Bug Report
Use mythicmobs to generate monsters, heights above 117 will not be able to spawn again
### Technical Information
* Server Software: 1.15.2
* Plugin Version:  V2.37-V2.39
* Dump File: 
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Use mythicmobs to generate monsters, heights above 117 will not be able to spawn again

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Use mythicmobs to generate monsters, heights above 117 will not be able to spawn again
2. every pet can,t
3. 
4. 

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/).

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.

**Free Speech**
I want you to fix this bug quickly, nothing more

**Comment by danielnaaman** [comment]
If the bug is clearly caused by the Mythic Mobs integration I'm not sure I understand what you expect **us** to fix.
