### ISSUE TITLE
WorldGuard Detector Broken

### ISSUE THREAD

**Issue by danielnaaman** [miniaturepets/issues#179]
# Bug Report

### Technical Information
* Irrelevant. 

### General Information

**Bug Description**
Please be as descriptive as possible when describing the bug you are facing, and save no words. Please use a reasonably understandable English, feel free to use stuff like Grammarly to do it.

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Install the plugin.
2. Make the first boot with the plugin.
3. Follow the instructions for WorldGuard spawn issues.
4. Reboot.

**Logs**
Please review this: https://pastebin.com/mW8NrWGK

**Free Speech**
1) This seems to be caused by some sort of extra check of WorldGuard configuration, after the configuration was actually altered.
2) Disabling `useWorldGuard` in the configuration file seems to resolve this issue.

**Comment by liorsl** [comment]
Will be fixed in the next version
