### ISSUE TITLE
Pets Behave Strangely Upon Interaction With Nether Portals

### ISSUE THREAD

**Issue by christaylor201** [miniaturepets/issues#180]
# Bug report

### Technical information
* **Server software:** Paper 1.15.2 build 229
* **Plugin version:** 2.4.0
* **Dump file:** None – I'm sorry, but I can't create the dump file using `/mpet dump`, it says there was a problem while exporting it. I guess it's due to our test server running on `localhost`.

### General information

**Bug description**
If a pet follows you and enters any kind of portal (Nether, End or even the custom one created by a plugin) while you don't, it will respawn at your position.

Then the pet will start behaving strangely, more precisely:
* it will stop pathfinding the owner, it will just wander around;
* the pet's GUI (opened by left-clicking on it) won't open;
* you will be able to take off its parts – custom heads, items, armor etc.

You have to remove the pet and resummon it to fix this issue.

**Instructions to produce**
1. Let a pet enter any kind of portal, but don't enter it yourself.
2. Observe its behavior.

**Logs**
This is the only message sent to the console when the pet enters a portal.
```
[18:34:40 WARN]: Ignoring unknown attribute 'miniaturepets.id'
```

**Visual demonstration**
https://streamable.com/24lkej

**Free speech**
In the previous version (2.3.9), a message would appear stating that the pet had been removed to prevent glitches when it entered a portal, however this feature doesn't seem to work properly in 2.4.0.

**Comment by danielnaaman** [comment]
That is most certainly a strange one, I've prioritized it. I hope it's not any kind of rush for you, might take at least a week or two to fix it. Assuming it's even a bug, we need to dig further into it.

**Comment by christaylor201** [comment]
It's okay, we've deployed your plugin only on the test server, therefore it's not that urgent.

**Comment by danielnaaman** [comment]
Sir, please update to the latest version and run `/mpet dump`, send us the output here.

Thanks.

**Comment by danielnaaman** [comment]
Just a quick update, I can't reproduce this issue.

Running latest paper, with nothing but Miniature Pets and WorldGuard installed.

One of your plugins is causing this, issue closed.

**Comment by christaylor201** [comment]
I've tried the version 2.4.1 on Paper 1.15.2 build 282, however the issue still persists, even if the only plugin installed is MiniaturePets as you can see in [the dump file](https://pastebin.com/hHjtmuFT).

Here's a [video](https://streamable.com/1e0abk) to prove it.

**Comment by danielnaaman** [comment]
Alright then, weird that I'm unable to recreate this. I'll have our developers take another look at it anyways.

**Comment by danielnaaman** [comment]
> I've tried the version 2.4.1 on Paper 1.15.2 build 282, however the issue still persists, even if the only plugin installed is MiniaturePets as you can see in [the dump file](https://pastebin.com/hHjtmuFT).
> 
> Here's a [video](https://streamable.com/1e0abk) to prove it.

Is there more then one person facing this issues? Or just you.

**Comment by christaylor201** [comment]
I don't know, to be honest, therefore I asked my colleague to reproduce the issue – I will let you know if he was successful or not.

**Comment by christaylor201** [comment]
Colleague of mine was able to reproduce the issue, here's a [video](https://youtu.be/FJyfmEqTiW0).

**Comment by danielnaaman** [comment]
What's your Minecraft client?

**Comment by danielnaaman** [comment]
Also, what's your Java version?

**Comment by christaylor201** [comment]
I use the official client; both the client and server run on Java 8 update 252.

**Comment by christaylor201** [comment]
Any updates on this issue?

**Comment by danielnaaman** [comment]
@christaylor201 I'm still unable to reproduce this, could you confirm this still happens with newer versions?

**Comment by christaylor201** [comment]
Unfortunately yes, I even tried it on a newly created server with PaperMC 1.15.2 build 375 and only MiniaturePets 2.4.3. Here's another [video](https://streamable.com/3je50u), but I don't think it will help.

**Comment by danielnaaman** [comment]
This has now been confirmed running the latest version of the plugin and of Paper.

*Note* It is a necessity to enter the nether portal in order to "trigger" the existence of a nether world before trying to put the pet through it, or the bug won't occur.

**Comment by christaylor201** [comment]
> It is a necessity to enter the nether portal in order to "trigger" the existence of a nether world before trying to put the pet through it, or the bug won't occur.

I apologize for not mentioning this – I'm glad you found out the exact conditions for reproducing the bug with the owner.

**Comment by danielnaaman** [comment]
Fixed, will be seen in the next version of Miniature Pets.
