### ISSUE TITLE
Miniature Pets Dump Generator Broken

### ISSUE THREAD

**Issue by danielnaaman** [miniaturepets/issues#182]
# Bug Report

### Technical Information
* Irrelevant.

### General Information

**Bug Description**
The dump command outputs an error and asks for a developer API key.

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Enter your server
2. Run `/mpet dump`
3. See the error

**Free Speech**
This only exists in the latest version, has to do with the recent dump file modifications.

**Comment by liorsl** [comment]
Will be fixed in the next version
