### ISSUE TITLE
MySQL Lags Upon Facing Connection Issues

### ISSUE THREAD

**Issue by Govindass** [miniaturepets/issues#183]
# Bug Report

### Technical Information
* Server Software: 1.12.2 paper
* Plugin Version:  2.4.0
* Dump File:  https://pastebin.com/t808hR9q (2.4.1 as of now, don't have dump from issue time)
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
MPets mysql connections can lag the server if mysql is having connection issues.

**Instructions To Produce**
I am not sure of the instructions, but my mysql server had stopped accepting remote connections for a short time due to unknown reason, which seems to have caused this issue
**Logs**
https://pastebin.com/raw/pQ2bBbDf

I reported it at AuthMe github at first, which is also having lag issues, but it combined with MiniaturePets in this case: https://github.com/AuthMe/AuthMeReloaded/issues/2109

**Comment by danielnaaman** [comment]
This will be fixed in the next version.

**Comment by Govindass** [comment]
when will this be fixed? because I am now regularly having issues with this lagging my server, I've solved all other lag causes and this is the last thing lagging it

**Comment by danielnaaman** [comment]
Your lags are caused due to your latency with your SQL server, the solution we will provide simply stop responding if the SQL server is causing too much lags. Again, this is barely a solution and will just stop your server from lagging but the fix is at your end..

**Comment by Govindass** [comment]
> 
> 
> Your lags are caused due to your latency with your SQL server, the solution we will provide simply stop responding if the SQL server is causing too much lags. Again, this is barely a solution and will just stop your server from lagging but the fix is at your end..

that is exactly what I need till I find how to solve the issue, it started since I switched my hosting provider from contabo to ovh, which is supposed to be more reliable

**Comment by danielnaaman** [comment]
Will be done on the next version, no ETA at the moment.

You can disable SQL for the time being.

**Comment by Govindass** [comment]
I found that all plugins using HikariCP do not have this problem for me, while those that don't use HikariCP have this problem. so a possible fix would be to switch MiniaturePets to using HikariCP, that'd also improve performance as HikariCP is very well optimized (even at bytecode level)

**Comment by danielnaaman** [comment]
Fixed! Thanks for your patience.

Will be seen in the next version.
