### ISSUE TITLE
When you name the pet, the name is way off centre.

### ISSUE THREAD

**Issue by LavivaNW** [miniaturepets/issues#185]
# Bug Report

### Technical Information
* Server Software: 1.12.2
* Plugin Version:  v2.4.1

### General Information

**Bug Description**
The name is far from the center when it is named in many pets.

This problem can be solved if we use a special armor as a nomenclature. We can place the armor according to the size and provide a perfect naming.

![image](https://user-images.githubusercontent.com/51966310/83317732-6636f480-a237-11ea-8f47-b7f2326bde54.png)

**Comment by danielnaaman** [comment]
Hi, I can't reproduce this, does this happen on a clean server as well? With no plugins?

**Comment by danielnaaman** [comment]
Please respond within 48 hours or this issue will close.
