### ISSUE TITLE
Error When Riding Pets due to using Netty Thread?

### ISSUE THREAD

**Issue by NickkTMD** [miniaturepets/issues#186]
# Bug Report

### Technical Information
* Server Software: Tuinity (https://github.com/Spottedleaf/Tuinity)
* Plugin Version:  2.4.1
* Dump File: https://pastebin.com/DMnjqYGE

### General Information

**Bug Description**
When clicking W to move forward while riding a pet you immediately get kicked.

I'm using Tuinity for its performance improvements. I brought this issue to them and they said that MPets is moving the pet entity on the netty thread or something like that, here's part of response I got:

"every block get call caused by that move call would've actually blocked on the main thread
so it would've negatively affected pings at high tick times
and it could corrupt some entity state"

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Use Tuinity server software
2. Ride a pet and click W to go forward

**Logs**
Error when trying to move on pet: https://pastebin.com/XGMqd11p

**Comment by danielnaaman** [comment]
Can you confirm it's the same issue as this one?

**Comment by danielnaaman** [comment]
Anyways, it's a work in progress, expect it by next release :)

**Comment by NickkTMD** [comment]
I'm not sure what you mean - same issue as what one?

Glad to hear it'll be fixed soon, thanks! ;)

**Comment by danielnaaman** [comment]
> I'm not sure what you mean - same issue as what one?
> 
> Glad to hear it'll be fixed soon, thanks! ;)

Ah, odd, I thought I gave you a link to an error log :P

Anyways it's apparently the same log as yours? So it's the same issue.

We're on it :dagger:

**Comment by liorsl** [comment]
Hello,
This bug will be fixed on the next version, thanks for reporting it!
