### ISSUE TITLE
Invalid config entries

### ISSUE THREAD

**Issue by N0tMyFaultOG** [miniaturepets/issues#187]
# Bug Report

### Technical Information
* Server Software: PaperMC
* Plugin Version:  2.4.2
* Dump File: http://haste.athion.net/jetibejete.css
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Please be as descriptive as possible when describing the bug you are facing, and save no words. Please use a reasonably understandable English, feel free to use stuff like Grammarly to do it.
Apparently I have improper materials in the config, tho I am using valid 1.15 material names.

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Setup a 1.15.2 server
2. Use my config and try to equip a pet

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/).
That happens on `/mpet reload`:
![](https://i.imgur.com/gvw405h.png)
If I try using `/mpet` this happens: ![](https://i.imgur.com/ffKNJ9L.png)
If I regenerate the file, I get this one but the error in the screenshot above persists: http://haste.athion.net/qupapevore.bash
This is my original file: http://haste.athion.net/korenedumo.coffeescript

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.
/

**Free Speech**
If you have anything left to say about this bug, that's the time to say it. It could be anything you want, this field is not required. Feel free to remove it.
/

**Comment by danielnaaman** [comment]
Hi,

Are you saying this happens with the default configuration?

Per my knowledge item names in Minecraft for some reason are not the same as the ones displayed to Minecraft users, meaning what you see in your inventory is not necessarily the actual material name you would use when creating a pet or when applying it to a configuration file.

Daniel.

**Comment by N0tMyFaultOG** [comment]
Yeah, if I try to use it I get this message
![](https://i.imgur.com/meD2RqZ.png)
but if I regenerate it my file has way less entries and it looks like that: http://haste.athion.net/uwomadesic.bash
And it chat it says that
![](https://i.imgur.com/aj2JHct.png)
So the file generates itself with invalid config entries but refuses to use mine which has been working for some time

**Comment by danielnaaman** [comment]
Just for testing purposes, back your Miniature Pets folder and afterwards wipe it clean, allowing the plugin to put in place everything that is default, let's see what happens then. Of course you can put everything back to it's place later, just want to make sure it is indeed not something within your configuration. Sorry for the hassle.

**Comment by N0tMyFaultOG** [comment]
Done, same issues as above. I'm still missing config entries apparently

**Comment by danielnaaman** [comment]
Ah, that's a weird one. Might I assume that your PaperMC is running on the latest build and that you are running Java 8?

**Comment by N0tMyFaultOG** [comment]
Got it sorted, thanks.
