### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by SlimeCody** [miniaturepets/issues#188]
# Bug Report

Running the latest version on spigot as of right now, dump file should not be needed for it. 

### General Information

**Bug Description**
The permissions seem to have been totally altered, the permissions preventing standard players from setting one anothers miniaturepets have been totally removed or they are not functional.

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Log two accounts on
2. Using the account with access to 1 of the pets, they can freely summon a pet for another player
3. using /mpet pet petname playername

**Visual Demonstration**
https://gyazo.com/5487cc0b8a497ffdbf60f580efc45d66

Buddy is just the alias we use in the command file

**Comment by danielnaaman** [comment]
Hi,

In order to approve your report I'd need to see your dump file, with that I can have more information on the issue that you are having.

Daniel.

**Comment by SlimeCody** [comment]
I will have to disclose it to you on discord for confidentiality reasons.

**Comment by danielnaaman** [comment]
This is still being investigated, I doubt that's even a bug. Conversation locked for the time being.

**Comment by liorsl** [comment]
The issue will be resolved in the next version, thanks for reporting it!
