### ISSUE TITLE
Pet Names Reset

### ISSUE THREAD

**Issue by ayseany** [miniaturepets/issues#189]
Server Software: Paper Spigot 1.8.8
Plugin Version: 2.4.2
Dump File: Contact me directly if needed.

Bug Description: When using MySQL to store pets data, players lose any custom name they set for their pet after despawning and then respawning the pet. The same applies in any situation when a pet is despawned and then respawned by the player. An SQL dump was set directly to Daniel, and I made sure that perPetName is enabled in config.yml.

Instructions To Produce: Set your pet's name, despawn your pet, then respawn the same pet.

Logs: No errors are reported in the console.

Visual Demonstration: https://imgur.com/a/upUVH4K

**Comment by danielnaaman** [comment]
Not opened using template, closed.
