### ISSUE TITLE
Pet Names Reset

### ISSUE THREAD

**Issue by ayseany** [miniaturepets/issues#190]
# Bug Report

### Technical Information
* Server Software: Paper Spigot 1.8.8
* Plugin Version: 2.4.2
* Dump File: Sent directly to Daniel for confidentiality reasons.

### General Information

**Bug Description**
When using MySQL to store pets data, players lose any custom name they set for their pet after despawning and then respawning the pet. The same applies in any situation when a pet is despawned and then respawned by the player. An SQL dump was set directly to Daniel, and I made sure that perPetName is enabled in config.yml.

**Instructions To Produce**
1. Set your pet's name
2. Despawn your pet
3. Respawn the same pet

**Logs**
No errors are reported in the console. SQL dump was sent to Daniel previously.

**Visual Demonstration**
https://imgur.com/a/upUVH4K

**Comment by danielnaaman** [comment]
Awaiting triage @liorsl :)

**Comment by Govindass** [comment]
can confirm this, been having this problem for ages

**Comment by danielnaaman** [comment]
Fixed, will be available in the next version.
