### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by arts7493** [miniaturepets/issues#194]
1. if pet head is load owner's head, cause critical error in console and only spawn armor stand and chicken
2. can't use Material's data on 1.15.2

Material: YELLOW_DYE

Material: INK_SACK
Data: 11

both doesn't work

**Comment by danielnaaman** [comment]
Sir, please follow the template we give members to create bug reports, also it seems like another duplicate of #171 and #193.

If it is, no need to reopen.

Thanks,
Daniel.

- Closed
