### ISSUE TITLE
Data not being read in versions above 2.3.8

### ISSUE THREAD

**Issue by Awpmeister2170** [miniaturepets/issues#195]
# Bug Report

### Technical Information
* Server Software: my server is 1.14.4 paper spigot
* Plugin Version:  currently using 2.3.8 so it works 

### General Information

**Bug Description**

Hello, today I did some investigating as some users have had issues with Pets not having the Correct items etc

After doing some tests myself I came to find out that Data information is not working in versions above 2.3.8 it seems Miniature pets isn’t looking for Data and keeps the ItemID the same ( here’s some Photos to help show what is going on
![A8776FD0-4D3B-47FD-81CD-EDFFF28137F1](https://user-images.githubusercontent.com/45782230/87425120-002ee280-c5d5-11ea-8abd-9f0fef08d8f4.jpeg)

![03033EFC-68F4-4339-B48E-88FCECA658ED](https://user-images.githubusercontent.com/45782230/87425149-09b84a80-c5d5-11ea-96e2-484727b41e47.jpeg)

In the first photo that is how it is suppose to look.

In any versions above 2.3.8 it doesn’t seem to change the Banner colour and keeps it the Default colour

I’m guessing it’s some sort of Data reading issue?

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Data issue just change versions and use a pet that requires different items to see
2. 
3. 
4. 

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/).

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.

**Free Speech**
If you have anything left to say about this bug, that's the time to say it. It could be anything you want, this field is not required. Feel free to remove it.

**Comment by danielnaaman** [comment]
Closed, duplicate.
