### ISSUE TITLE
Add Denizen Support

### ISSUE THREAD

**Issue by incredimike** [miniaturepets/issues#196]
Please consider adding [Denizen support](https://www.spigotmc.org/resources/denizen.21039/) into Miniature Pets.

I originally asked the Denizen developers if they could support your plugin, and they suggested it would require implementation on the Miniature Pets side. 

Right now I chain Denizen scripts -> Mythic Mobs -> Miniature Pets. Would be nice to cut out Mythic, if possible!

(Adding this to Github issues by request from support. Sorry for filing a "bug" i couldn't find a "feature" issue type.)

**Comment by danielnaaman** [comment]
Sorry but we don't intend to do this anytime soon, we have an API and the developer of Denizen can easily make the adjustments necessary for his plugin to work with Miniature Pets. He is also welcomed to contact us and ask for help with the implementation.

Good day.
