### ISSUE TITLE
Mpet with Mythicmob causes error spam and server crash

### ISSUE THREAD

**Issue by ZubeySweet** [miniaturepets/issues#201]
**Bug Description**
When using mythic mobs to disguise a zombie as an MPET, it sometimes will spam errors then crash the server. It did not use to do this, since there were 5 months or so where we never had a problem, and I have not added anything new to conflict. The only things I can think of that may have started it is the fact we updated Mpets, or are using the newest paper jar, or went from Java 11 on our server to Java 14? Here are the error logs below that show the specific Mpet error being spammed and all the technical info from the server.

EDIT: I also went and tested the previous 2 versions on miniaturepets and those did the same thing.

**Error Logs:** https://codeshare.io/GkOVJA

### Technical Information
User Identifier: 748091
Download Nonce: 1060165076
Online Status: True
Plugin Version: 2.4.4-beta
Source: SpigotMC
Server Platform: PaperMC
Server Version: v1_15_R1
 
Plugin List:
 * AdvancedMonthlyCrates version 1.9.256
 * ParrotAnnouncer version 3.0.2
 * PlaceholderAPI version 2.10.9
 * MMOLib version 1.2.4
 * Damager version 1.0.0
 * UltraCustomizer version 1.4.2
 * Mazes version 1.0.0
 * ChatReaction version 1.8.0
 * CommandPrompter version 0.1.19
 * DeluxeTags version 1.8.1
 * Pedestal version 1.0.0
 * LagAssist version 2.20.3
 * ItemEditor version 0.1.9
 * WorldEdit version 7.1.0;8e55131
 * PlayerInformation version 2.9
 * Skript version 2.4.1
 * PacketListenerApi version 3.7.7-SNAPSHOT
 * VillagerOptimiser version 1.1.2
 * BuycraftX version 12.0.6
 * Votifier version 2.7.1
 * Vouchers version 2.1.0
 * HealthScale version 1.0
 * DivineDrop version 2.5.9
 * InteractiveBooks version 1.5.1
 * Celeste version 1.51
 * UltraPermissions version 4.7.1
 * CrazyCrates version 1.10-RELEASE
 * WorldGuard version 7.0.3;5407315
 * ViaVersion version 3.1.0
 * ViaBackwards version 3.1.0
 * WorldEditSUI version 1.7.1
 * GrapplingHook version 3.5
 * Vault version 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
 * WorldGuardEvents version 1.0
 * ViaRewind version 1.5.1
 * MiniaturePets version 2.4.4-beta
 * UltraSouls version 1.0.0
 * RepairGui version 6.5.4
 * Companions version 1.7.11
 * ShopGUIPlus version 1.31.2
 * UltraSkills version 1.0.0
 * PyroFishingPro version 3.10.10
 * Essentials version 2.18.0.3
 * MarriageMaster version 2.2.7-Release
 * PinataParty version 2.7.7
 * Citizens version 2.0.26-SNAPSHOT (build 1951)
 * UltraFarm version 1.0.5
 * TradeSystem version 1.1.13
 * Plan version 5.1 build 624
 * DeluxeMenus version 1.13.2-Release
 * Lottery version 1.4.3
 * XPBoost version 3.4.1
 * JumpPads version 1.24.19
 * CitizensCMD version 2.5
 * BlockParticles version 1.11.1-RELEASE
 * CustomOreGen version 1.3.27-SNAPSHOT
 * CMI version 8.7.6.12
 * AdvancedEnchantments version 7.14.6
 * EpicSpawners version 6.4.2
 * FabledSkyBlock version 2.3.8
 * ProtocolLib version 4.5.1
 * Multiverse-Core version 4.1.1-SNAPSHOT-bUNKNOWN
 * LibsDisguises version 10.0.15
 * VotingPlugin version 5.22
 * TAB version 2.8.3
 * AuctionMaster version 2.3
 * Images version 2.0.5
 * MythicMobs version 4.10.0-SNAPSHOT-SNAPSHOT
 * BossShopPro version 2.0.8
 * GhostScavengerHunt version 2.2.3-SNAPSHOT
 * GadgetsMenu version 4.5.23
 * ChatControl version 5.8.9
 * MMOItems version 5.5.3-SNAPSHOT
 * HoloMobHealth version 2.0.6
 * CMIPaperLib version 1.0.0

**Comment by danielnaaman** [comment]
We currently do not provide support for issues related to Mythic Mobs, as they are caused by the Mythic Mobs extension.
