### ISSUE TITLE
Add option to allow right click pet to mount

### ISSUE THREAD

**Issue by Karagra** [miniaturepets/issues#202]
I was told to put this here as a request, pretty much add an option in config to allow right click pet will auto ride pet, I would imagine GUI would also have to be turned off.

**Comment by danielnaaman** [comment]
The functionality has been created, we hope to implement it in the upcoming versions. It depends on our release schedule.

Thanks for your suggestion!

**Comment by Karagra** [comment]
Ahh perfect! not I forgot to ask because I do not create them myself... Does mpets have a option to allow / not allow ride per pet.. Like in the file of the pet add ride: false ?

**Comment by danielnaaman** [comment]
> Ahh perfect thanks so much! I forgot to ask because I do not create them myself... Does mpets have a option to allow / not allow ride per pet.. Like in the file of the pet add ride: false ?

No we don't, we probably won't add that either.
Sorry.
