### ISSUE TITLE
Miniaturepets is no longer anchored to mythicmobs

### ISSUE THREAD

**Issue by Gorderok** [miniaturepets/issues#208]
Mythicmobs made with miniature animals spawn and drop dies when spawned on miniaturespets version 2.5
or, as there was already with old version of miniaturepets (1.13/1.14), the miniaturepets anchor is not attached to the mythicmobs, only the mythicmobs (invisible) spawn
No console error

Miniaturepets 2.4.4
![2020-09-18_17 03 12](https://user-images.githubusercontent.com/43994828/93666993-d7b6df00-fa82-11ea-9ccb-1f0c0628d3ab.png)

Miniaturepets 2.5
https://www.youtube.com/watch?v=IosAbO3Pcnk&ab_channel=DavidR
![2020-09-19_14 36 29](https://user-images.githubusercontent.com/43994828/93667433-19955480-fa86-11ea-8fc7-536a3e752969.png)

**Comment by danielnaaman** [comment]
Hi, I'm sorry but we really can't code the entire plugin based on the MythicMobs extension, since the extension is developed by them or by their community, it's their job to adapt to our changes.
