### ISSUE TITLE
[Feature Request] Blacklist Pet Names

### ISSUE THREAD

**Issue by GregKW** [miniaturepets/issues#210]
Could you guys please add a config that can blacklist pet names like the N-word or whichever word we choose

**Comment by danielnaaman** [comment]
I like the idea, I'll have to put this on hold for now though since we focus our attention on other things.

At some point I definitely think we'll implement this.

**Comment by GregKW** [comment]
> I like the idea, I'll have to put this on hold for now though since we focus our attention on other things.
> 
> At some point I definitely think we'll implement this.

Thanks

**Comment by danielnaaman** [comment]
This has been added and will be implemented in future version. (Hopefully 2.5.2)
