### ISSUE TITLE
Allow customization of no perms icon

### ISSUE THREAD

**Issue by GregKW** [miniaturepets/issues#211]
Hello, Can you please add an option to keep the regular perm icons because just showing blocks as the pet icons when you don't have perms is really ugly and I would prefer there be an option for this, Also add lores to the pets so we can put a description of the pet and the buycraft store so players know where they can buy it 👍

**Comment by danielnaaman** [comment]
Hi, what icon are you referring to? And you can edit pet lores by editing the pet file.

This can be done using any zip opener like winrar or 7zip, just open the pet file as an archive.

**Comment by GregKW** [comment]
> Hi, what icon are you referring to? And you can edit pet lores by editing the pet file.
> 
> This can be done using any zip opener like winrar or 7zip, just open the pet file as an archive.

I'm talking about this, https://gyazo.com/9f32824b293b30ae17ec6dfd1dd7d81a

**Comment by danielnaaman** [comment]
Never seen that before. Please reopen your bug report according to the template, so I can handle it. Make sure to include all of the information.

Thanks a lot
