### ISSUE TITLE
[Feature Request] Hide Pets If No Permissions

### ISSUE THREAD

**Issue by GregKW** [miniaturepets/issues#212]
# Feature Request

### General Information

**Feature Description**
When a player doesn't own any pets and you set hideIfNoPerms: false all the pets displayed have clay blocks shown instead of the pet heads can you please make it so it shows the pet heads or add an option to set it like that

**Visual Demonstration**
When players own the pets they see this https://gyazo.com/ca71eb6529852c7203410527c8901a7a However when they don't own any pets it shows this https://gyazo.com/1bf3a6c61d6d2227a7c2df666099b368 Please add an option to always show the pet heads.

**Comment by danielnaaman** [comment]
@UltraFaceguy Config option should be: `hideIfNoPerms: true/false` - If true, pets won't show, stay as default state. If false, pet heads should show as they always do, but in the pet name or in the lore it should say clearly, **no permission**.

**Comment by danielnaaman** [comment]
Implemented, will be seen in 2.5.2
