### ISSUE TITLE
[Feature Request] Configuration option 

### ISSUE THREAD

**Issue by GregKW** [miniaturepets/issues#213]
# Feature Request

### General Information

**Feature Description**
Please add an option to enable right and left-click on a pet and when a player right-left clicks a pet it can show the store link and tell the user who the pet belongs to **example:**

- This pet belongs to {name}
- Want your own pet?
- Purchase at buy.example.com

**Comment by danielnaaman** [comment]
This feature is denied, too general and speficic for your needs, probs will be rarely used.

You can easily hire a developer for something like this.

We've already added something similar in #202
