### ISSUE TITLE
[Feature Request] GUI Customisability

### ISSUE THREAD

**Issue by EwansXD** [miniaturepets/issues#218]
- Add the ability to change the max slots in the GUI
- Add the ability to change which slots the pets will be in on each page
- Add the ability to change which slots the page, rename, remove and teleport buttons are in
- Add the ability to disable the rename button in the GUI
- Add the ability to fill the empty GUI slots with a specificed item

**Comment by EwansXD** [comment]
Another option instead of the filler could just be adding dummy items that do nothing

**Comment by danielnaaman** [comment]
Please reopen according to template.
