### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by PhanaticD** [miniaturepets/issues#220]
# Bug Report

### Technical Information
* Server Software: tuinity (paper fork) 1.15.2
* Plugin Version:  2.5.4
* Dump File: https://pastebin.com/raw/MadPBZpY
> Use `/mpet dump` to get the dump file.

### General Information

I am getting this error https://pastebin.com/raw/NZ70LFp9

the gui was not working and it was suggested to reset it, so i deleted petGUI.yml and did /mpet reload and this error pops up and the GUI continues to still not work

**Comment by danielnaaman** [comment]
If I remember correctly you resolved this by yourself? @PhanaticD
