### ISSUE TITLE
[Bug Report] Pets turn into "Drowned" mob

### ISSUE THREAD

**Issue by Brandon3140** [miniaturepets/issues#221]
# Bug Report

### Technical Information
* Server Software: Tuinity 1.16.4 (latest)
* Plugin Version:  2.5.4
* Dump File: 
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
If you're near a body of water in-game and you have a pet, and if your pet is in the water for an extended period of time, it will become the "Drowned" mob

**Instructions To Produce**
1. Summon your pet near an ocean (or create a sphere of water using worldedit or something)
2. Go into the water, and make sure your pet is fully engulfed in it
3. Wait a few minutes
4. Your pet will turn into the drowned mob, with no sign of where the pet went.

**Logs**
No errors are caused.

**Visual Demonstration**
Video: https://www.youtube.com/watch?v=afOo4wr5maI

**Comment by danielnaaman** [comment]
My mind tells me that this is a mistake :(
Are you sure about the numbers of versions? We fixed that bug (confirmed) 6 months ago.

Daniel
