### ISSUE TITLE
[Feature Request] Add actual pet name and per pet settings.

### ISSUE THREAD

**Issue by Elioz** [miniaturepets/issues#222]
Hello,

We already discussed on discord about it,
so basically, when I summon a pet, the placeholder %petname% shows the pet filename and not the pet actual pet name as appear in the pet config file.
Since my server is fully translated, I need it to show the actual pet name,

Second thing is an idea to add "Per pet settings" like if is possible to ride on specific pet or renaming specific pet.

Thanks in advance!

**Comment by liorsl** [comment]
Hello Elioz,

I am very sorry that it took so long for us to respond. In order to not break existing installation we have added your request as the variable `%petdisplayname%`. 

About per pet settings, do you mean doing so via permissions?

**Comment by Elioz** [comment]
awesome! thanks!
for example in each pet configuration settings, you can add
rideable: true/false
rename: true/false 
etc.

**Comment by liorsl** [comment]
Will be available in the next version as well :)
