### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by GregKW** [miniaturepets/issues#224]
# Bug Report

### Technical Information
* Server Software: Paper
* Plugin Version:  Latest
* Dump File: 
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Every time a player logs in the console gets spammed with this, https://pastebin.com/30YmYuQG
**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. every time a player logged in that spam would go through console https://pastebin.com/30YmYuQG

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/).

**Visual Demonstration**
https://pastebin.com/30YmYuQG

**Comment by liorsl** [comment]
Hello, 

Thanks for reporting this issue. The problem will be resolved in the next release.
