### ISSUE TITLE
Plugin Fails on Startup

### ISSUE THREAD

**Issue by Awpmeister2170** [miniaturepets/issues#225]
# Bug Report

### Technical Information
* Server Software: 
* Plugin Version: 2.5.4 
* Dump File: 
> Cant get on the server to get a Dump file so here is a alternative  https://pastebin.com/pZkg49Gu

### General Information

**Bug Description**
Hello the Plugin was Working perfectly fine as im a Pet creator and help on the Support side so this really confused me, the Server started up as normal but when i joined i got times out and went to console and seen this  https://pastebin.com/pZkg49Gu

would love to know why it has happened, ( Turning off Check for Updates has fixed it for now )

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Server Restarted
2. Went to rejoin and got the error
3. No idea what caused it sorry
4. 

**Logs**
 https://pastebin.com/pZkg49Gu

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.

**Comment by liorsl** [comment]
Hello,

This issue will be resolved in the next version.
