### ISSUE TITLE
[Feature Request] In-Game Editor

### ISSUE THREAD

**Issue by Hipopotofobia** [miniaturepets/issues#227]
# Feature Request

### General Information

**Feature Description**
I would like a simple in-game editor for pets via command or menu

EX: /pet rename (name)
/pet reperm (permission)
/pet desc (description)

This will help new people to Mpets or people who don't know exactly how to edit them be able to change simple text.

**Comment by liorsl** [comment]
Hi,

I am not too sure what you mean by that suggestion. Players can rename their pets as it is.

Can you please explain?

**Comment by Hipopotofobia** [comment]
/pet rename would rename the desired pet
/pet reperm would change the permission of the pet
/pet desc would change the description of the pet

**Comment by danielnaaman** [comment]
Denied.

It's a waste of development resources, it can be done manually just by editing the file and it should be something you do perhaps once in your server's lifetime. I doubt a command is in order here.

Good day and stay safe.
