### ISSUE TITLE
[Bug Report] Minipets like zombies, skeletons and foxes pick up items of players

### ISSUE THREAD

**Issue by XxMissGueraxX** [miniaturepets/issues#228]
# Bug Report

### Technical Information
* Server Software: PaperSpigot 1.16.4 Java
* Plugin Version: 2.5.4
* Dump File: https://pastebin.com/7ZrXziqt
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
I installed the minipets pack "Default Vanilla Mob Pack! 1.2" by Awpmeister2170. When I was trying the minipets out, I noticed that some minipets can grab dropped items from players. It's about the following minipets of the minipets pack:
- husk
- fox
- zombie
- drowned
- skeleton
- stray
- so every mob that can hold items from players in vanilla
When a minipet has an item, you can't get it back. You can't kill the minipet and it won't drop the item when you remove the minipet. So you're items are doomed.. I didn't get any errors when restarting the server to add the minipets, nor did I get any errors when using the minipets or when it grabs an item.

**Instructions To Produce**
1. Install the minipets pack "Default Vanilla Mob Pack! 1.2" by Awpmeister2170
2. Be OP to have permission for all minipets
3. Use a minipet like drowned
4. Give a piece of armor or a sword and the minipet will grab the item

**Logs**
I don't have errors or weird stuff in my logs when restarting the server.

**Visual Demonstration**
![2021-01-20_18 36 51](https://user-images.githubusercontent.com/70282501/105213447-020ecb00-5b4f-11eb-8aca-90d882177a78.png)

**Comment by liorsl** [comment]
Hello,

After testing the specific pack and pet you have mentioned I was not able to reproduce this issue, it may be related to interference by another plugin. What happens when you try with no plugins?

**Comment by XxMissGueraxX** [comment]
It appears to be indeed something else that is creating this bug and not the plugin itself. I tested the plugin on a test server, and no minipets pick up stuff. Now I need to figure out which of my other plugins or any setting I use is interfering.

**Comment by XxMissGueraxX** [comment]
Today I tested on a basic server with only miniature pets plugin on, and the fox picks up stuff you throw at it. So even without any other plugins that mob still picks up things and that shouldn't be possible. Tho, it seems that the hostile mobs don't pick up stuff on this basic server. So I think it's best for you to try it out with a fox so you can see what happens.

**Comment by UltraFaceguy** [comment]
Not a bug with the pack, but rather the anchor entity (usually a chicken, in this case, tons of different mobs) seems to be able to grab things. Support for random different mobs, especially hostile ones, was always shaky at best, and usually, people just didn't use them.

This pack simply opened a big can of worms 😅

In any case, I'm working on a fix 👍

**Comment by danielnaaman** [comment]
This bug has been fixed and will be implemented into the next version of Miniature Pets.

Thanks for your report 💘
