### ISSUE TITLE
[Bug Report] Players are invincible 

### ISSUE THREAD

**Issue by AccioAce** [miniaturepets/issues#229]
# Bug Report

### Technical Information
* Server Software: Paper 1.16.5
* Plugin Version:  Version: v2.5.5 
* Dump File: (I wasn't able to get the dump file) Sorry.
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
I'm having the same issue with Version: v2.5.5 Miniature, players seems to be disappearing and appearing. We cannot see them in the tab list. It's like they are invincible to each other.

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/). I do not see errors in the console.

**Comment by GrilledCow** [comment]
Same issue with v2.5.5 here, I've already downgraded but I didn't see any errors in console. Players that joined after I joined were visible and shown in the tablist if that's any help.

**Comment by danielnaaman** [comment]
This has been fixed in the v2.5.6 update :D
