### ISSUE TITLE
[Feature Request] Ability to Fly on pets

### ISSUE THREAD

**Issue by LavivaNW** [MiniaturePets/Issues#238]
# Feature Request

### General Information

I want the pets we ride on to be able to fly. To determine this pet, the pets specified as "pet-fly: true" in the settings file must be able to fly. for example, we made aircraft pets. When we get on the plane, we should be able to fly as we want.
There is a similar plugin that did this before. The vehicles plugin has done this before.

Example from the aircraft model in the vehicle plugin.
![110977229-f7b0c680-8372-11eb-9403-634548101f84](https://user-images.githubusercontent.com/51966310/110984744-97268700-837c-11eb-8668-11e53d498afd.png)

**Comment by DanielNaaman** [comment]
We've decided to drop this feature request for the meanwhile, we're facing a huge load of requests and currently switching developers. This might be relevant in 2022, and I encourage you to suggest it again then.

Sorry
