### ISSUE TITLE
[Bug Report] Prefix in Lang.yml Doesn't Affect All Commands

### ISSUE THREAD

**Issue by Dancull47** [miniaturepets/issues#239]
# Bug Report

### General Information

**Bug Description**
The prefix within lang.yml doesn't seem to carry over to all the messages it should

It works properly for the permission command, but not anything else it seems
![AFUDbEs](https://user-images.githubusercontent.com/36930553/111419769-6e75f880-86c0-11eb-8615-9faa9d6c98c1.png)

**Comment by danielnaaman** [comment]
Hello there, please open a ticket with us via our Discord server, we don't use GitHub as a platform for individual errors, only for bug reports. 

Our Discord link can be found on the "New issue" button.

**Comment by liorsl** [comment]
Hello,
Sorry for the issue being closed.
Can you elaborate on which messages exactly dont have the prefix?

**Comment by Dancull47** [comment]
> Hello,
> Sorry for the issue being closed.
> Can you elaborate on which messages exactly dont have a prefix?

My mistake, I have realized that the prefix does change for all messages upon restarting server. It only changes for some when reloading.

**Comment by liorsl** [comment]
Very well. 
Note that there are 2 fields, `prefix` and `chatPrefix` and you need to change both. 
Locking this one.
