### ISSUE TITLE
[Bug Report] Animations on Armorstands with a yaw "toggle"

### ISSUE THREAD

**Issue by LordRazen** [MiniaturePets/Issues#240]
# Bug Report

### Technical Information
* Server Software: Paper version git-Paper-288 (MC 1.16.4)
* Plugin Version: v2.5.6
* Dump File: https://pastebin.com/VXRzUk0d

### General Information

**Bug Description**
Animations on Armorstands with a yaw "toggle" around instead of doing a clean animation (see test pet)

The test pet include one armorstand which work correctly (since he has no yaw) and the one with yaw is bugged.

**Instructions To Produce**
Checkout the attached test pet (you have to rename it to .mpet)
[DarkCar+NewWheels.zip](https://github.com/miniaturepets/issues/files/6177275/DarkCar%2BNewWheels.zip)

**Visual Demonstration**
![YawBug](https://user-images.githubusercontent.com/9381368/111902926-f866ee00-8a3f-11eb-8613-7c804c012d34.gif)

**Comment by liorsl** [comment]
Hi,
From what I gathered setting `IDLE_run_once` to true in the pet yml will resolve that issue.
Can you confirm making said change will result in the intended behaviour?

**Comment by LordRazen** [comment]
Hi, I can check this during the next few days, but I wonder: This setting clearly states that the idle animation should run once, but it's not about running it one or multiple times. it's about correcting the teleport position of armorstands with yaw other then 0. will be impossible for pet creators in future to associate that this bug can be solved with the (totally unknown and undocumentated) option idle_run_once ;-)

Maybe you could add some details about this parameter what it should do, so I can test it better. Thx ^^

**Comment by LordRazen** [comment]
Tested. Didnt help :-/
[DarkCar+NewWheels.zip](https://github.com/miniaturepets/issues/files/6235415/DarkCar%2BNewWheels.zip)

(Just rename the attach .mpet to test it. But git doesnt accept .mpet as file format, so I had to rename it)
