### ISSUE TITLE
[Bug Report] Yaw for pets without animation

### ISSUE THREAD

**Issue by LordRazen** [MiniaturePets/Issues#241]
# Bug Report

### Technical Information
* Server Software: Paper version git-Paper-288 (MC 1.16.4)
* Plugin Version: v2.5.6
* Dump File: https://pastebin.com/VXRzUk0d

### General Information

**Bug Description**
If there're armorstands with a yaw different then 0, there's a chance they got a strange position while moving around. 

Example: Orange Concrete blocks still have a yaw different then 0
![FahrtBug](https://user-images.githubusercontent.com/9381368/111916183-f752b280-8a79-11eb-9963-1a223ed50830.gif)

Example 2: Orange concrete blocks are fixed to yaw = 0
![FahrtBug2](https://user-images.githubusercontent.com/9381368/111916189-0174b100-8a7a-11eb-9359-d92b3c44ffdb.gif)

You can clearly see that they don't have bugged position during the movement anymore.

The bug goes in the same direction as the bug linked below, but it appears on a different spot:
https://github.com/miniaturepets/issues/issues/240

While this bug appears in the regular movement of the pet, the issue 240 appears for animations.

However, it's both the yaw.

**Comment by liorsl** [comment]
See my reply to #240 

> From what I gathered setting IDLE_run_once to true in the pet yml will resolve that issue.
Can you confirm making said change will result in the intended behaviour?
