### ISSUE TITLE
[Feature Request] Documentation for the configuration.

### ISSUE THREAD

**Issue by LordRazen** [MiniaturePets/Issues#243]
# Feature Request

It would be great to have a full documentation of the configuration tags for pets (the configs for the plugins are documentated, there's nothing to do here ;-)). 

I know there's this tutorial: https://miniaturepets.net/threads/creating-a-pet.4/
But it only covers a part of the possibilities. 

**items.yml:**
I found the tags "Material", "SkullURL" and "Color" here. But are there any others? Like I would really love to have tags for banners, too (will make a feature request for this if you tell me there's no possibility for those). 

**model.yml**
The model also includes many tags, like the "anchor" for the animal behind the model, the "speed" for the riding speed and "API" and "static" which aren't really explained anywhere. This knowledge have to be documentated somewhere or the feature is useless. :-/

Other possibilities: There might be tags which I never found in pets since they're not documentated, so I cannot ask about them. But the feature request should be clear: A full documentation for pets  ;-)

**Comment by danielnaaman** [comment]
I completely agree, we are slowly adding documentation, but you've covered it all here, I'm almost a 100% certain that these are all the possibilities, and I've explained them to you in private I believe. Either ways, we'll document them in the coming months.

**Comment by DanielNaaman** [comment]
Hey, it's a work in progress, but we're doing it : https://docs.getminiaturepets.com/configuration/general-settings

Step by step we'll add the rest
