### ISSUE TITLE
[Feature Request] Improvement of the Plugin GUI

### ISSUE THREAD

**Issue by LordRazen** [miniaturepets/issues#244]
# Feature Request
The symbols used in the Plugin are gui are absolutly not intuitive. Why the dye icons?

I suggest to change them:

**Icons when you rightclick on the pet**
Ride your pet:
- Actual: light blue day
- Suggestion: Saddle

Name your pet:
- Actual: cactus dye
- Suggestion: Nametag

Remove pet:
- Actual: red dye
- Suggestion: barrier block (shown as a red cross in the GUI)

Disguise pet:
- Actual: light blue dye
- Suggestion: chestplate

**Icons when you type /mpet:**
Remove your pet:
- Same as above...

Teleport your pet:
- Actual: light blue dye
- Suggestion: leash

While doing this, I found a typo: "To undisguise use the disguise command **agian**"
I know I can fix this in my config, but it should be fixed in the default config.

**Comment by danielnaaman** [comment]
Hey, sounds interesting!
It'll be very helpful if you could put everything into a chest so I can see how it actually looks.

**Comment by LordRazen** [comment]
![Unbenannt](https://user-images.githubusercontent.com/9381368/112630856-79562900-8e36-11eb-97b4-c43d1f54800e.png)

**Comment by danielnaaman** [comment]
Approved, will be implemented in the next version.

**Comment by liorsl** [comment]
I have changed the defaults per your suggestion.
Existing installations however will not enjoy it at first, you might need to remove relevant config entries / files. 

Thanks for the suggestion!
