### ISSUE TITLE
[Bug Report] Animation is not calculated correctly according to the "quality" animation setting between last frame and default state

### ISSUE THREAD

**Issue by LordRazen** [miniaturepets/issues#246]
# Bug Report

### Technical Information
* Server Software: Paper version git-Paper-288 (MC 1.16.4)
* Plugin Version: v2.5.6
* Dump File: https://pastebin.com/VXRzUk0d

### General Information

**Bug Description**
There's no valid calculation for a smooth animation between the last and the first frame. The pet jumps from the state which is setup in the last frame to the default state, while it calculates a smooth transition between the other frames.

**Example: Default Position + 3 Frames**

Default state:
`headPos: "{0 , 0 , 0}"`

Frames:
```
F1
armorstand001:
 headPos: "{0 , 0 , 90}"
 
F2
 armorstand001:
 headPos: "{0 , 0 , 180}"

F3
armorstand001:
 headPos: "{0 , 0 , 270}"
 ```

Result:
![Example1](https://user-images.githubusercontent.com/9381368/113128950-a598ed80-921a-11eb-9c4d-022afe4a5ebc.gif)

You can clearly see it starts in the default position (head goes up), then go to frame 1 (90° , right), frame 2 (180°, down) and frame 3 (270°, left) and then jumps back to the default position. 

**So the bug here: Within the mpet.yml, you set a "quality" for the animation which calculates the steps inbetween the different frames. This is ignored for the last frame.**

If you now saw: just add another frame with the default state - this might work for simple mpets, but as soon as there're multiple animated armorstands, there's another bug which enslows the animation for yet unknown and not clearly reproduceable reasons. I'll try to find a clear pattern, but this will be a lot easier if the first bug is fixed already...

**Example**
Just rename the file to .mpet and you can see the problem.
[AnimationRotationBug.zip](https://github.com/miniaturepets/issues/files/6235853/AnimationRotationBug.zip)

**Comment by danielnaaman** [comment]
I think this is a great suggestion, although this might take a while from what I can infer. I've set it to the version after the next in terms of milestones. We'll see if we can add it to this version (no promises!).

**Comment by danielnaaman** [comment]
Also, I'm not sure if I should count it as a feature or a bug, so let's go with both.

**Comment by LordRazen** [comment]
Clearly a bug: The frame duration from the config is ignored for the last frame ;-)

**Comment by UltraFaceguy** [comment]
So I reached out to Razen and talked about it, and I don't think that this one should be done. One can 'finish' the animation simply by adding a fourth frame (headPos: "{0 , 0 , 360}") and the animation will smoothly complete. This is how it's always been, and while I think it would be BETTER to smoothly finish animations, a lot of existing pets would begin to stall on animation loops, as they were designed with the system as it is. Considering you can already achieve the desired effect, and changing how it works would break backwards compatibility, I'm going to close this, but keep it in the back of my head in case we ever seen to do a breaking change to animations.
