### ISSUE TITLE
[Feature Request] Anchor Variant Config Option

### ISSUE THREAD

**Issue by LordRazen** [miniaturepets/issues#247]
# Feature Request
For the anchor pet, there're often variants like for rabbits or horses. Add a tag how you can control this and use a certain variant.

If this tag exists already, add it to the documentation since nobody knows about it :D

# Update 12th April:
I just recognized there's a baby tag already: `baby: true`, however... it wasnt documentated, but another pet bundle started using it ^^

**Comment by danielnaaman** [comment]
Hey, do you mean something like a Zombie Pig-Man or a baby pig?

**Comment by danielnaaman** [comment]
> Would also fit, yes. Here're a few examples:
> 
> * Horse: Variant - there's a free pet for a unicorn. when I spawned this pet it was black. I always thought those are supposed to be white :D
> * Rabbit: Variants (realised this when I wanted to ensure a brown easter rabbit, not a black one)
> * Size (isBaby) would surely also be a great option for the anchor.
> 
> but if you plan to add multiple options, it might be a good idea to group the settings in the mpet.config:
> 
> ```
> anchor:
> - type: horse
> - isBaby: false
> - variant: 123 etc...
> ```

It's not documented I agree haha, you can do this, you just need to get the right pet ID, I have no clue which these are, it's a bit a game of trying and failing until you get it right. We tried once to assemble a list but Mojang doesn't publish this information so it's a real pain in the ass. If you are looking for specific ones, you should ask in #create and I'm confident someone will have the answer.

**Comment by LordRazen** [comment]
Hm, I'm not sure if Bukkit is so different here, but Minecraft doesnt save the color variant of a Horse (for ex) in the entity type. So there's nothing like "horse:0" or "horse_brown" I could use as anchor.

Here's an example for entity data (result of (`/data get entity` on a horse):

The variant tag decides about the look. https://minecraft.fandom.com/wiki/Horse#Appearance
Same exists for rabbits and other mobs...

```
Horse has the following entity data: {Paper.SpawnReason: "SPAWNER_EGG", DeathTime: 0s, Bukkit.MaxDomestication: 100, Bukkit.updateLevel: 2, LeftHanded: 0b, OnGround: 1b, AbsorptionAmount: 0.0f, AgeLocked: 0b, Attributes: [{Name: "minecraft:generic.follow_range", Modifiers: [{Name: "Random spawn bonus", Amount: 0.02770345180610306d, Operation: 1, UUID: [I; -1752003582, 1153713960, -1938544459, 1713934023]}], Base: 16.0d}, {Name: "minecraft:horse.jump_strength", Base: 0.7610093272864059d}, {Name: "minecraft:generic.max_health", Base: 20.0d}, {Name: "minecraft:generic.movement_speed", Base: 0.25321746131298345d}, {Name: "minecraft:generic.armor", Base: 0.0d}], Invulnerable: 0b, Brain: {memories: {}}, Paper.Origin: [-2602.5d, 66.0d, -1527.5d], Age: 0, Bukkit.Aware: 1b, HandDropChances: [0.085f, 0.085f], Rotation: [-87.21356f, 0.0f], ArmorDropChances: [0.085f, 0.085f, 0.0f, 0.085f], HurtByTimestamp: 378, ForcedAge: 0, WorldUUIDMost: -8966309706660099951L, ArmorItems: [{}, {}, {}, {}], Temper: 0, Air: 300s, HandItems: [{}, {}], **Variant: 518**, UUID: [I; 1517616413, -10203558, -2051207378, -195672852], Tame: 0b, Spigot.ticksLived: 566066, Bred: 0b, InLove: 0, FallDistance: 0.0f, WorldUUIDLeast: -8607258127304329362L, Motion: [0.0d, -0.0784000015258789d, 0.0d], Pos: [-2602.3017578125d, 66.0d, -1527.3017578125d], Fire: -1s, CanPickUpLoot: 0b, Health: 20.0f, HurtTime: 0s, FallFlying: 0b, PersistenceRequired: 1b, EatingHaystack: 0b, PortalCooldown: 0}
```

I'm a bit confused what you mean with "Mojang doesn't publish this information". The info is just right above ;-)

**Comment by liorsl** [comment]
Its gonna be available in the next version!
https://miniaturepets.net/threads/using-pet-anchor-metadata.5/
Thank you for the suggestion!
