### ISSUE TITLE
[Feature Request] Pet Loader should strip colors when getting pets

### ISSUE THREAD

**Issue by keyute** [MiniaturePets/Issues#249]
# Feature Request

### General Information

**Feature Description**
Please be as descriptive as possible when describing the feature you desire, and save no words. Please use a reasonably understandable English, feel free to use stuff like Grammarly to do it.

Colors in the name of a pet is a front-end aspect for the player, but has side effects in the back-end such as using pet names as keys in YAML, where & symbol is regarded as anchors.

**Visual Demonstration**
This can be drawings or sketches you've made, pretty much anything to help us better understand your suggestion.

**Comment by danielnaaman** [comment]
What do you think of this? @liorsl

**Comment by liorsl** [comment]
It would be very tricky to fix.
Can you elaborate on where exactly that causes problems?

**Comment by DanielNaaman** [comment]
@keyute Please respond within 48 hours or this issue will be closed.

**Comment by keyute** [comment]
Closed this as I have done another implementation to get pet instances
