### ISSUE TITLE
[Feature Request] Support organized .mpet files

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [miniaturepets/issues#252]
# Feature Request - Organizing your .mpet files

### General Information

**Feature Description**
I would like to see a change in the plugin where Miniature Pets will scan its pet folder and all subdirectories for .mpet files.

Currently the plugin only supports reading .mpet files in the  `/plugins/MiniaturePets/pets/` directory.
When I created `/plugins/MiniaturePets/pets/default` it would not detect and enable the .mpet files in the "default" directory.

What I'm suggesting is feature I've seen in other plugins that may have many files. It'd be nice if Miniature Pets detected subdirectories to allow easier management of pet files when there are many of them. The example paths below would all be valid locations since they are belong to /pets/ or a subdirectory of /pets/.
```
/plugins/MiniaturePets/pets/
/plugins/MiniaturePets/pets/donorgroup/
/plugins/MiniaturePets/pets/donorgroup2/
/plugins/MiniaturePets/pets/donorgroup2/secret/
/plugins/MiniaturePets/pets/donorgroup3/
```

I don't know if there's a performance concern about implementing this feature (like longer server start up time) but if it is then this behaviour can be made `false` by default.

**Comment by liorsl** [comment]
Hello,
Since I think its a very nice feature to have you can expect seeing it in the next version.
Thanks for the suggestion!
