### ISSUE TITLE
Pet stuck in air and cant be despawned.

### ISSUE THREAD

**Issue by FaZz129** [miniaturepets/issues#253]
Hi I had the turtle glitch out and get stuck in the air by a player. They cannot despawn it cause it doesnt believe they have a pet active and I cant manage to remove it. It is ruining my spawn cause its in the middle of it and the name is just floating there aswell. I removed most of the heads for the pet
![2021-05-09_00 21 16](https://user-images.githubusercontent.com/33965199/117560525-86cd1880-b05c-11eb-9ca7-7d2bc15406dc.png)

**Comment by danielnaaman** [comment]
Hi, please open again according to the template.
