### ISSUE TITLE
[Bug Report] Horses as Anchor cannot be controlled while riding the pet

### ISSUE THREAD

**Issue by LordRazen** [MiniaturePets/Issues#254]
# Bug Report

### Technical Information
* Server Software: Paper version git-Paper-288 (MC 1.16.4)
* Plugin Version:   v2.5.6
* Dump File: https://pastebin.com/VXRzUk0d

### General Information

**Bug Description**
If you ride the pet (which is usually a invisible chicken), you can also control the pet with the arrow keys. Not for horses - they cannot be controlled if used as anchor. I guess they're not tamed. I didnt check mules and donkeys.

**Instructions To Produce**
https://miniaturepets.net/resources/unicorn-pets-%E2%9C%94-animation-%E2%9C%94-quality-design-and-model-%E2%9C%94-%E2%9C%AA-new-%E2%9C%AA.395/
Test out this public pet ;-)

**Comment by liorsl** [comment]
Hello,
I have actually tested it with your pet and couldn't reproduce the issue.
Maybe there is another step?

**Comment by LordRazen** [comment]
Your pet? You mean this unicorn? Just making sure we mean the same cause it's not my pet, I just recognized it while using it. 

I tested it again with 2.5.9 stable and... I definitly cannot call this "riding on a horse". It's more like shifting a bit in the direction before stopping again...

Would it help if I send the whole server setup? It's a local testserver, there's not much in there...

**Comment by liorsl** [comment]
Are you refering to the riding speed? I believe you can change that via pet anchor properties.

**Comment by LordRazen** [comment]
Here you go: https://ibb.co/F3gq13N

This here has nothing to do with a setup riding speed... this is just buggy. Test it yourself plz, I linked the pet - and it's not about THIS pet, it's the horse anchor in general.
