### ISSUE TITLE
[Feature Request] Placeholders

### ISSUE THREAD

**Issue by Askarionn** [MiniaturePets/Issues#256]
# Feature Request

### General Information

**Feature Description**
Placeholders for Collectibles Menu like Hypixel
Example placeholders: %miniaturepets_pets% (it will say how many pets do you, based on permissions i think?)
%miniaturepets_pets_percentages% (it will say the percentage of pets that player have)

Can be usefull if you have a collectibles menu and you want to add an item for MiniaturePets

**Visual Demonstration**
![2021-05-29_01 20 12](https://user-images.githubusercontent.com/51824859/120046956-0aef3c00-c01c-11eb-800a-d63594fc8d0a.png)

**Comment by DanielNaaman** [comment]
@liorsl Don't we have this already?

**Comment by DanielNaaman** [comment]
Will be added in the next-next version.

**Comment by liorsl** [comment]
Hi,
Thanks for suggesting this.
These are the placeholders I have added so far:

- [ ] currentpet: Will display the name of the current pet you have spawned
- [ ] available_player_pets: Will show the names of pets you have
- [ ] unlocked_pets: Will show the amount of pets you have
- [ ] all_pets: Will show the amount of all the pets you have access to

We are using https://www.spigotmc.org/resources/placeholderapi.6245/
It will be available in the next version.
Enjoy!
