### ISSUE TITLE
[Feature Request] prevent mounting pet bypass worldguard region's entry permission

### ISSUE THREAD

**Issue by Kwstv** [MiniaturePets/Issues#260]
# Feature Request

### General Information

**Feature Description**
Please be as descriptive as possible when describing the feature you desire, and save no words. Please use a reasonably understandable English, feel free to use stuff like Grammarly to do it.

as the title said, i hv set a region with entry: false, and required groupmanager group. it works probably without mounting pet. the region push me out when i entry. But when im riding a pet, it doesn't push me out until i get off the pet

**Visual Demonstration**
This can be drawings or sketches you've made, pretty much anything to help us better understand your suggestion.

**Comment by liorsl** [comment]
A patch for this issue will arrive in the next release.
