### ISSUE TITLE
[Feature Request] Permission for multiple pets

### ISSUE THREAD

**Issue by Lordinouill** [MiniaturePets/Issues#261]
# Feature Request

### General Information

**Feature Description**
Be able to give players permission for a number of simultaneous pets summoned.
In such a way users could have up to 2, 3, etc pets at the same time.

If the maximum amount of pets is reached and the player click to summon a new one, the oldest is replaced.

Would look like mpet.amount.2 for 2 mpets

**Visual Demonstration**
I think the first explanation is quite explicit ask me if you need more details

**Comment by DanielNaaman** [comment]
You mean someone can spawn 2 pets simultaneously for instance?

**Comment by Lordinouill** [comment]
> You mean someone can spawn 2 pets simultaneously for instance?

Yup exactly they could have 2 pets at the same time following you

**Comment by DanielNaaman** [comment]
Suggestion ignored.

This would cause a lot of hassle in the server and can block the player's vision often, especially when it comes to huge pets. It might be possible in the future. For now this is less relevant.
