### ISSUE TITLE
command to keep pets

### ISSUE THREAD

**Issue by PandaKeny** [MiniaturePets/Issues#264]
mypet plugin-like pet storage command (/petsendaway)

**Comment by DanielNaaman** [comment]
Hello, how is this different then despawning a pet?

**Comment by UltraFaceguy** [comment]
From my understanding, this is a way to set a 'favorite pet' that can be re-summoned by /pet call or login or whatever, without actually re-selecting the pet from the picker. Basically stores the pet as a 'favorite' or 'default' pet until you pick a new one

**Comment by liorsl** [comment]
Hello,
If you want to keep pets when logging in and out you just need to set ``respawnPetOnJoin`` to true.
Does that help?

**Comment by PandaKeny** [comment]
it will be like mypet plugin (/petsendaway) to send pet somewhere. If you want to summon the pet again, /pet call

**Comment by liorsl** [comment]
Does that command despawn the pet?

**Comment by DanielNaaman** [comment]
Closed due to lack of response, please reopen according to template next time.

**Comment by PandaKeny** [comment]
![image](https://user-images.githubusercontent.com/87780831/179373943-75496944-6392-47ec-aa79-216c74dccff9.png)
I've been buying it for a long time, but I can't download it right now.
