### ISSUE TITLE
[Bug Report] Custom Model Data not working in 1.17 version

### ISSUE THREAD

**Issue by pacificminer** [MiniaturePets/Issues#265]
Hello. 

Custom Model Data support is not in the latest MiniaturePets version for 1.17 (build 259). 
It worked in the previous builds for 1.16. A fix for this would be appreciated!

Paper: 124 for 1.17.1
Plugin: 259

**Comment by liorsl** [comment]
Hello,
I believe you have implemented our quick fix already, otherwise you can expect the fix to be included in the next version.
