### ISSUE TITLE
[Feature Request] Make the Anchor Position of the Pet changeable

### ISSUE THREAD

**Issue by LordRazen** [MiniaturePets/Issues#267]
# Feature Request
Right now, the pet is anchored like two blocks behind the player. 

For some pets, it might be useful to place them at another position - like directly at the player. 

If you do this with the existing possibilities, the pet is moving around the player instead that it's kept directly at the player.

Here's an image to show what I mean:
![grafik](https://user-images.githubusercontent.com/9381368/126949576-d14fa5f0-6626-4c2b-8eff-633aa128382a.png)

**Comment by liorsl** [comment]
Hello,
This seems to be the same as #281 so I am closing this one.
Thank you for the suggestion!
