### ISSUE TITLE
[Feature Request] Make armor stands fully rotatable

### ISSUE THREAD

**Issue by feroxmc** [MiniaturePets/Issues#270]
# Feature Request

So currently from what I have seen, armor stands have to face the same direction the pet is going. This makes it harder to do certain things.

**Feature Description**
So I suggest that similar to armor stand editor plugins out there, armor stands become able to be rotated fully. Instead of having them face one solid direction like the 1st image has you can have it face another direction to the side.
**Visual Demonstration**
This 1st image shows a way similar to how we have it now.
![Screenshot 2021-08-05 001218](https://user-images.githubusercontent.com/37503543/128307676-37f2aa20-c649-4421-b48b-f7547d484770.png)
However let's say that we have it so that you can rotate the armor stand completely, having one going straight and one facing to the side like here.
![Screenshot 2021-08-05 001419](https://user-images.githubusercontent.com/37503543/128307799-1c13d5b7-44a1-41b9-9f00-12770a1ad8ed.png)

**Comment by liorsl** [comment]
Hello,
I am not sure how this feature would be useful - armor stand direction are always relative to the pet direction.
Making some stands have static direction could make the pet look broken.

**Comment by feroxmc** [comment]
Hello,

Yes, I made this awhile ago before I realized I might have messed somrthing
up on my part that made it seem like this was needed. I believe I have
found a way around it.

**Comment by DanielNaaman** [comment]
Glad to hear that!

Issue closed
