### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by ITrustLovesCoding** [MiniaturePets/Issues#271]
I am having an issue its saying "oh no your pet is being removed when spawned because of another plugin."
I want to know how to fix that issue because I looked in console and logs and it doesn't say what plugin. It just told me to report it to you guys on github.
Plugin: miniaturepets

**Comment by DanielNaaman** [comment]
Hey, please open a ticket on our Discord server. This is usually due to WorldGuard.

Access the WorldGuard configuration and set `block-plugin-spawning` to `false`.

That should do the trick. In any other case, ticket us. This isn't a bug, rather a fix at your end.
