### ISSUE TITLE
[Bug Report] disguise toggling making players disappear in 1.17.1

### ISSUE THREAD

**Issue by jiajunmao** [MiniaturePets/Issues#274]
# Bug Report

### Technical Information
* Server Software: Paper 1.17.1, Build 243
* Plugin Version: v2.5.9
* Dump File: https://pastebin.com/1Gy5LLdc
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
When the player disguise as a pet, and try to undisguise by using the `/pet disguise` command, the player disappears (or does not appear). This behavior was not observed prior to 1.17.1 update. Switching server and coming back in a bungee setup solves this problem. 

**Instructions To Produce**
1. Do `/pet disguise` and disguise as pet
2. Do `/pet disguise` again
3. Poof! You are gone!

**Logs**
There are no exceptions thrown in the console.

**Visual Demonstration**
https://cdn.discordapp.com/attachments/749361696824492124/872423283897827328/2021-08-04_15-03-11.mp4
(Borrowed from a previous report)

**Comment by jiajunmao** [comment]
Just curious, any updates on this?

**Comment by DanielNaaman** [comment]
> Just curious, any updates on this?

We're currently making some changes in our development team, patience is necessary I'm afraid.

**Comment by DanielNaaman** [comment]
Hey, we've resolved this in the upcoming update.

Your patience is highly appreciated.
