### ISSUE TITLE
[Bug Report] ChunkLoadListener.ChunkLoad causing Stackoverflow and Thread Death

### ISSUE THREAD

**Issue by jiajunmao** [MiniaturePets/Issues#277]
# Bug Report

### Technical Information
* Server Software: Paper 1.17.1
* Plugin Version: 2.6.0
* Dump File: https://pastebin.com/bG4aapg5
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Please see the pastebin report attached below. Although I am not 100% positive that mpet is the culprit, the stacktrace does make it look suspicious. ChunkLoadListener.ChunkLoad seems to be triggering itself in an infinite loop causing thread death.

**Instructions To Produce**
Not really sure there is a definitive trigger. Just let the server run and it just happens.

**Logs**
https://pastebin.com/zhP8piDt

**Comment by DanielNaaman** [comment]
Hello, you are running v2.5.9

Please update and verify the issue also happens there. 

Also, could you post the output of `/ver`?

Daniel

**Comment by jiajunmao** [comment]
Ah sorry for the confusion, I think I have pasted the wrong link that I used for another issue.
Here is the correct dump link https://pastebin.com/bG4aapg5 and yes the problem occurs with 2.6.0 (edited in the issue report as well)

The /ver output is: `This server is running Paper version git-Paper-243 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 20903fc)`

**Comment by DanielNaaman** [comment]
Are you running the latest paper build?

**Comment by jiajunmao** [comment]
I think reading more into the paper issue and PR, I am almost certain that the issue mentioned above is the root cause. I have updated to the latest paper build and MP hasn't been causing any trouble yet, so I think we can consider this issue resolved.
