### ISSUE TITLE
[Bug Report] Pet NPC's not spawning correctly after update/restarts

### ISSUE THREAD

**Issue by Loving11ish** [MiniaturePets/Issues#278]
# Bug Report

### Technical Information
* Server Software: paper 1.17.1-283
* Plugin Version:  v2.6.0
* Dump File: https://pastebin.com/biCiZS1v
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
After updating my server to 1.17.1, the pet npc's no longer spawn or if they do, they don't spawn in correctly. (MiniMe is a full sized armour stand, one has become a chicken etc.)  The plugin also generated the following error 3 times in the console after a restart: 'WARN Uh oh... A pet failed to spawn due to another plugin! Please report this athttps://github.com/miniaturepets/issues/issues with your plugin list and any errors so we can help! :)'

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Update from 1.16.5 to 1.17.1.
2. Simply started the server.
3. The above error then occurs.
4. 

**Logs**
https://pastebin.com/xEejSKT7

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.

**Comment by liorsl** [comment]
Hello,
The error you have received means a 3rd party plugin is interfering with MiniaturePets.
Unfortunately we cannot help you with that, you will have to find out which plugin causes this issue.

Have a nice day!
