### ISSUE TITLE
[Bug Report] [MiniaturePets] [STDOUT] Error in open inventory

### ISSUE THREAD

**Issue by Tomographix** [MiniaturePets/Issues#279]
# Bug Report

### Technical Information
* Server Software:  Airplane version git-Airplane-95 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
* Plugin Version:  2.6.0
* Dump File: https://pastebin.com/NZTjx02k

### General Information

**Bug Description**
Hi,
This error keeps spamming in console:
[MiniaturePets] [STDOUT] Error in open inventory
[MiniaturePets] [STDOUT] Error in open inventory
[MiniaturePets] [STDOUT] Error in open inventory

**Instructions To Produce**
Start the server.
Error will spam the console quite consistently.
The error will occur every 2 seconds or so.

**Logs**
Server startup log: https://pastebin.com/6hU9XqK8

**Comment by liorsl** [comment]
Hello,
I apologize for the delay in response.
Please enable debug mode and send over the errors.

**Comment by DanielNaaman** [comment]
More than 72 hours has passed with no response, we now assume the issue is resolved.

If the issue persists, please reopen issue with the information requested in the three dots ( * * * ).


> Hello,
> I apologize for the delay in response.
> Please enable debug mode and send over the errors.
