### ISSUE TITLE
[Feature Request] Pets reappear after restart.

### ISSUE THREAD

**Issue by DrizzyySP** [MiniaturePets/Issues#280]
**Feature Description:**
I would like an option to be added to the settings that would allow users' pets to reappear after the server restarts.

Currently if the server restarts players have to reselect the pet after joining, I would like the pets they had selected before the server restart automatically reappear as it is already done after relogin, or changing worlds.

**Comment by liorsl** [comment]
Hello,
A feature exist which would allow exactly what you are looking for.
For pet spawn when a player joins the server: `respawnPetOnRejoin`
For pet spawn on world change: `respawnPetOnWorldMove`
You can find both these options in `config.yml`.
