### ISSUE TITLE
[Feature Request] Adjusted how close the pet will be to us.

### ISSUE THREAD

**Issue by chadedas** [MiniaturePets/Issues#281]
# Feature Request

### General Information

**Feature Description**
I want in Config.yml to have something that can adjust how many blocks away the pet will follow us.
Since I have a problem, the pet is too far away from me. until I don't know whose pet this is exactly :l
So I'd like you to add a feature that counts ,how many blocks away the player is from a pet. Pets will then follow and follow. Then How many blocks will they far distance from us? This is just my idea that I would like to explain to you. Sorry I use a translator. hope you can understand

**Visual Demonstration**
For example, I adjusted that the pet will start following me after I am 3 blocks away from the pet.
![Capture](https://user-images.githubusercontent.com/64877724/139910653-9fa6bdf5-6c58-41c2-83e0-70450b17d74e.JPG)

For example, I adjusted that the pet will start following me after I am 1 blocks away from the pet.
![Capture1](https://user-images.githubusercontent.com/64877724/139910848-f9bde52c-73ef-4c47-91e4-e8b7a716fa4d.JPG)

For example, I adjusted that the pet will start following me after I am 0 blocks away from the pet.
![0block](https://user-images.githubusercontent.com/64877724/139910937-cb27c119-0a03-4d59-8a44-e4383eb5ec13.JPG)

**Comment by liorsl** [comment]
Hey,
Thank you for the suggestion.
This feature will be available on the next release.

Have a nice day!
