### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by tdvne** [MiniaturePets/Issues#282]
# Bug Report

### Technical Information
* Server Software: SpigotMC
* Plugin Version:  2.6.0
* Dump File: https://pastebin.com/DsTBcPh3
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Please be as descriptive as possible when describing the bug you are facing, and save no words. Please use a reasonably understandable English, feel free to use stuff like Grammarly to do it.

Basically, I load up the plugin normally, then go to spawn it in-game, and boom, it despawns, I gbo check console, and it tells me to come here.

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Load Up Plugin
2. Do /pet
3. Then try to spawn it
4. Then it won't spawn

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/).

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.

**Comment by DanielNaaman** [comment]
Fixed in latest release, will be released soon

**Comment by tdvne** [comment]
> Fixed in latest release, will be released soon

Still does not work.
