### ISSUE TITLE
[Bug Report] Animations don't work when I use pets as hats.

### ISSUE THREAD

**Issue by LavivaNW** [MiniaturePets/Issues#283]
# Bug Report

### Technical Information
* Server Software: 1.12.2
* Plugin Version:  2.6.1

### General Information

**Bug Description**
In older versions, animations worked when we used pets as hats. lost this feature in new versions.

**Visual Demonstration**

https://i.hizliresim.com/htkg1tq.gif

**Comment by DanielNaaman** [comment]
I actually find it cleaner that way, some animations really took over the head and made the pet look messy.

For now I'll keep it like this.
