### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by dinobossytnew** [MiniaturePets/Issues#286]
Feature request

### General information

**Feature Description
In-game pet builder using an in-game pet builder with a menu and an unlimited 3d architecture like AdvancedSpawners but pets would be much easier for new and old users of the plugin where the yml and similar configurations are in the past and we walk into the future, example in this menu using chat obviously we could put names, life, what the pet eats, make animations by moving the heads in-game and of course the heads are changed either using a link or id of a head or name if the head is premium.
next I leave pictures of how it could be and how the animations would be saved and seen in a menu where each animation will tend ribbons as a part of each animation as we do in blockbench as the same 1 x 1 movements are created. 
GC PLUGIN images were not made by me.

**Visual Demonstration**.

![mobEditor](https://user-images.githubusercontent.com/58078116/145853158-c3ae37cb-0599-4950-84e5-14dea78ea0cd.gif)
![9d3148ed400a7b553e14ef7adf96d63d0a79cce9](https://user-images.githubusercontent.com/58078116/145853219-f771b9b7-e05a-4e0a-8045-dce3e0936d1f.png)
![a956258336f4dcccb300d3404637760081c83ab3](https://user-images.githubusercontent.com/58078116/145853222-7fb51ea8-c119-429d-8291-b35c1c12134f.png)
![f4b87204405f2e8cbf6fe7a43773816a427c6388](https://user-images.githubusercontent.com/58078116/145853227-b395b5a1-7fe1-4cd7-824d-cacafe208f18.png)

**Comment by DanielNaaman** [comment]
Hello, this feature request will be placed in suggestions for v3.0 and will be closed for the time being. It requires a massive update to our code which will not happen before v3.0

Thanks a lot for your creativity

Daniel

**Comment by dinobossytnew** [comment]
ok
