### ISSUE TITLE
Bedrock Client Pet Issue [Bug Report] 

### ISSUE THREAD

**Issue by Monjiigames** [MiniaturePets/Issues#287]
Hello Developer,

As we are all aware, more and more servers are becoming compatible with Bedrock Clients now. However, obviously due to Bedrock having their own client limitations, it'll be impossible to make pets visible for them, however I wanted to ask for a feature to be added or the bug to be fixed whereby pets appear as steve heads for bedrock users.

One way to go around this is to make the pets "invisible" for bedrock clients, and only visible for java

**Comment by DanielNaaman** [comment]
Hi, we 100% don't support Bedrock clients and for the time being we don't plan to focus our development efforts into it, it takes hiring developers that know their way around both and we just focus on the majority of our users now. Sorry.

Additionally, we require to use the bug report template.
