### ISSUE TITLE
Placeholders Problem

### ISSUE THREAD

**Issue by Askarionn** [MiniaturePets/Issues#288]
# Bug Report

### Technical Information
* Server Software: Debian 10
* Plugin Version:  2.6.2
* Dump File: -
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
The placeholder "%miniaturepets_unlocked_pets%" display the number of available pets, not the unlocked pets

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Be sure you're not OP / you don't have any pets
2. /papi parse me %miniaturepets_unlocked_pets%
3. See the problem

**Logs**
-

**Visual Demonstration**
https://www.youtube.com/watch?v=gpKBh6Fn7xg

**Comment by DanielNaaman** [comment]
Whoopsy 

We'll get to it after the 1.18.x update.

Please note that server software is intended to be your Paper/Spigot version. (The JAR you use)

**Comment by Askarionn** [comment]
i'm using Nacho

**Comment by DanielNaaman** [comment]
Hello, we've applied the fix and it will be released in the upcoming version.
