### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by Awpmeister2170** [MiniaturePets/Issues#290]
# Bug Report

### Technical Information
* Server Software:
 Paper version 1.8.8 up to 1.17.*
* Plugin Version:  
2.5.8 up to the latest the issue persists
 Dump File: 
N/A no errors appear 

### General Information

**Bug Description**
Hello, I have been testing the Pet metadata due to the Baby: true not working ( plus others like the angry wolf etc.
In version 2.5.7 ( the last  working version ) the baby: true works but the wolf still doesn’t I think this needs to be looked into

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. N/A but all I can say to help is 2.5.7 works fine for the baby metadata but not the others.

**Logs**
N/A no errors appear 

**Visual Demonstration**
N/A for this bug

**Comment by liorsl** [comment]
Hi!
Daniel sent me the pet.yml file.
The `baby` field needs to appear inside the `anchor` or `anchorProperties` field like documented here:
https://miniaturepets.net/threads/using-pet-anchor-metadata.5/
Otherwise it will not work.
