### ISSUE TITLE
[Bug Report] Pet Sit doesnt work

### ISSUE THREAD

**Issue by LagClear** [MiniaturePets/Issues#293]
# Bug Report

### Technical Information
* Server Software: PaperSpigot
* Plugin Version:  1.18.1
* Dump File: https://pastebin.com/vCky9HxT
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Running /pet siit doesnt work message goes through but still teleports around when I move around

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. /pet sit

**Comment by LagClear** [comment]
plugin version 2.6.3

**Comment by DanielNaaman** [comment]
Fixed. Will be present in upcoming update.
