### ISSUE TITLE
[Bug Report] Pet disguise is buggy

### ISSUE THREAD

**Issue by LagClear** [MiniaturePets/Issues#294]
# Bug Report

### Technical Information
* Server Software: Paperspigot 1.18.1
* Plugin Version:  2.6.3
* Dump File: https://pastebin.com/vCky9HxT
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Right clicking the pet to disguise works but as soon as you switch a pet in the /pets menu it keeps me invincible when I reopen the menu to undisguise or use the command it doesn't do anything and keeps me invincible.

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Select A Pet
2. Right click pet
3. Click Disguise
4. Switch pet and try to undisguise or use the command

**Comment by LagClear** [comment]
Relogging seems to fix the issue but happens every time

**Comment by DanielNaaman** [comment]
This is supposedly fixed now. The fix will appear in the upcoming update.
