### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by Hekzo** [MiniaturePets/Issues#296]
1.  Pet is removed right away.
2. Console says this "WARN Uh oh... A pet failed to spawn due to another plugin! Please report this athttps://github.com/miniaturepets/issues/issues with your plugin list and any errors so we can help! :)"

**Comment by DanielNaaman** [comment]
Hello, please open a ticket on our Discord server by running /new

Thanks

**Comment by Hekzo** [comment]
What's the discord?

**Comment by DanielNaaman** [comment]
https://discord.gg/6rTwkmynd8
