### ISSUE TITLE
[Bug Report] A pet failed to spawn due to another plugin!

### ISSUE THREAD

**Issue by Officer502** [MiniaturePets/Issues#297]
# Bug Report

### Technical Information
* Server Software: java
* Plugin Version:  2.6.4
* Dump File: https://pastebin.com/FMrBxUAv
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
When you try to spawn a pet you receive this error message in console. (Uh oh... A pet failed to spawn due to another plugin! Please report this athttps://github.com/miniaturepets/issues/issues with your plugin list and any errors so we can help! :))

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. /pet
2. choose any pet
3. pet spawns
4. pet is removed

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/).

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.
[url=https://ibb.co/nzgFzT3][img]https://i.ibb.co/nzgFzT3/Capture.png[/img][/url]

**Comment by DanielNaaman** [comment]
Hello, please open a ticket on our Discord server.
https://discord.gg/6rTwkmynd8
