### ISSUE TITLE
[Bug Report] 1.9.4 Hat Issue

### ISSUE THREAD

**Issue by Awpmeister2170** [MiniaturePets/Issues#298]
# Bug Report

### Technical Information
* Server Software: Spigot / PaperSpigot 1.9.4
* Plugin Version:  unreleased V2.6.4
* Dump File: NA 

### General Information

**Bug Description**
1.9.4
Hat issue still persists, when pet is used as a hat the pet spins around on top of your head.

**Comment by GC-spigot** [comment]
Fixed
