### ISSUE TITLE
[Bug Report] 1.17.1 Hat Issue

### ISSUE THREAD

**Issue by Awpmeister2170** [MiniaturePets/Issues#299]
# Bug Report

### Technical Information
* Server Software: Spigot / PaperSpigot 1.17.1
* Plugin Version:  Unreleased V2.6.4
* Dump File: 
NA

General Information:

1.17.1 
Hat issue when the pet is used as a Hat it spins around on your head constant

https://gyazo.com/652d3551e52d959607f5d5a9f76e360e

All versions you are able to punch the pet when riding still which causes you to glitch / fly in the air ( this needs fixing asap as players can glitch with it )

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Load on to the server versions I stated 
2. Run the commands above that I mentioned 
3. 
4. 

**Logs**
NA

**Visual Demonstration**

**Comment by GC-spigot** [comment]
Fixed
