### ISSUE TITLE
[Bug Report] Anchor variants

### ISSUE THREAD

**Issue by Sjarlotte** [MiniaturePets/Issues#302]
# Bug Report

### Technical Information
* Server Software: purpur1.18.1
* Plugin Version:  2.6.4
* Dump File: https://pastebin.com/ir53cDHR
> Use `/mpet dump` to get the dump file.

### General Information
**Bug Description**
Unable to use the new "variant" option for anchors to spawn in a blue axolotl

**Instructions To Produce**

1. adding [variant] to axolotl anchor makes the file not load.
2. tested with other formats, error on [axolotlStyle] and [style] and [color]
3. missing the examples to test on mobs like horses and cats as the basic pet format is not yet updated on the new website

**Logs**
![image](https://user-images.githubusercontent.com/92209204/153290129-0ce66141-7389-416b-98af-b0b8fa0518f3.png)
![image](https://user-images.githubusercontent.com/92209204/153290203-ef6d98a8-45fd-4f9e-9abe-19863264bd14.png)

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.

![image](https://user-images.githubusercontent.com/92209204/153290985-8f169a30-77f9-4e3f-a464-69244bf8d15b.png)

**Comment by ghost** [comment]
resolved will be present in next update
