### ISSUE TITLE
Pet Baby Zoglin attacks me

### ISSUE THREAD

**Issue by Plattio** [MiniaturePets/Issues#303]
# Bug Report

### Technical Information
* Server Software:  Paper v1_18_R1
* Plugin Version:  2.6.3
* Dump File: https://pastebin.com/v5aMEaAt
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
If i spawn a baby zoglin as a pet - it attacks me.

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1.  Spawn baby zoglin
2.  Walk against it and it will attack you

**Comment by Plattio** [comment]
Is there any ETA for the bugfix?

**Comment by Awpmeister2170** [comment]
Did the latest update resolve your issue?

**Comment by Plattio** [comment]
Yes

**Comment by Awpmeister2170** [comment]
Perfect!
