### ISSUE TITLE
[Bug Report] when player join serverm, player teleport to pet & pet name height issue.

### ISSUE THREAD

**Issue by Ecilpse** [MiniaturePets/Issues#304]
# Bug Report

### Technical Information
* Server Software: windows server 2021
* Plugin Version:  2.6.8
* Dump File: https://pastebin.com/pBBhyn5i
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
1. after update, player are teleport to pet
when player swith to other server (bungeecord)
when player switch server, player teleport to mpet.
some people are complain of this problems

3. after update, pet name tags are appears below pet.
![2022-03-27_14 43 14](https://user-images.githubusercontent.com/25452835/160268489-9d38625e-6c0f-48f1-b074-098108aaf011.png)

after update, 

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. 
2. 
4. 
5. 

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/).

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.

**Comment by GC-spigot** [comment]
Can you provide a GIF or a Video to the 1st issue? Thanks

**Comment by GC-spigot** [comment]
Fixed second issue

**Comment by Ecilpse** [comment]
> Fixed second issue

https://www.youtube.com/watch?v=d-d-j4ZF1Qo
