### ISSUE TITLE
[Bug Report] Error in the console caused by InventoryClickEvent and InventoryCloseEvent

### ISSUE THREAD

**Issue by w8fyz** [MiniaturePets/Issues#305]
# Bug Report

### Technical Information
* Server Software: Custom PaperSpigot 1.8.9
* Plugin Version:  "v${project.version}" (???????? I just downloaded it from SpigotMC)
* Dump File: https://pastebin.com/zNvzYXfX

### General Information

**Bug Description**
Im using a NMS class using a villager inventory, and when I close the inventory or click on it, an error appear, it seems that MiniaturePets's event (InventoryClickEvent and InventoryCloseEvent) don't check if the inventory is from the miniaturepets plugin and detect every inventory opened by other plugins.

A solution is simple :
When MiniaturePets open an inventory, store it in an arraylist, when calling InventoryCloseEvent and InventoryClickEvent, check if the event inventory is in the arraylist.
Hope this help.

**Instructions To Produce**
1. Create a plugin opening a villager inventory
2. Click on the inventory or close it
3. The error appear in the console

**Logs**

Error on InventoryClickEvent :

![image](https://user-images.githubusercontent.com/35635613/167942020-bbe3e3fb-d667-42c9-b1d3-b297bb0aa0c4.png)

Error on InventoryCloseEvent :

![image](https://user-images.githubusercontent.com/35635613/167942223-dfe0f7fa-912d-4eaf-9ab4-393aed15297e.png)

**Comment by Saharo4eks** [comment]
Update to 2.7.1

**Comment by Awpmeister2170** [comment]
Fixed

**Comment by w8fyz** [comment]
Thanks :)
