### ISSUE TITLE
[Bug Report] Problems due to pets colliding with players.

### ISSUE THREAD

**Issue by Saharo4eks** [MiniaturePets/Issues#307]
# Bug Report

### Technical Information
* Server Software: git-Purpur-1623 (MC: 1.18.2)
* Plugin Version: 2.7.0 
* Dump File: https://github.com/MiniaturePets/Issues/issues/306

### General Information

**Bug Description**
If a player is standing near a wall, he will push you behind it when the pet appears. In world_the_end this is a critical moment.

**Instructions To Produce**
1. Stand near the wall
2. Summon a pet

**Visual Demonstration**
https://imgur.com/a/BiGa86n

**Comment by Awpmeister2170** [comment]
Fixed
