### ISSUE TITLE
[Bug Report] Variable bugs

### ISSUE THREAD

**Issue by Ecilpse** [MiniaturePets/Issues#308]
# Bug Report
i uploaded video in AE discord channel, and moderator said submit issue here.

1. when modelengine pet after spawned, pet are still walking even though it's stopped.
2.can't riding
3. hex code are not supported? 
4. can't set nameplate with modelengine pet

### Technical Information
* Server Software: Purpur 1.18.1 Ro.1
* Plugin Version:  lastest (2.7.1)
* Dump File: https://pastebin.com/b85tM57u
> Use `/mpet dump` to get the dump file.

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. make modeled pet.
2. summon pet.
3. walk around & riding & rename

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/).
![unknown](https://user-images.githubusercontent.com/25452835/168675532-8ab08db7-61b6-40ac-a586-2e53df5da202.png)

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.
i uploaded video in AE discord channel.

**Comment by GC-spigot** [comment]
Added hex color support
