### ISSUE TITLE
Pets Walking Animation Lag

### ISSUE THREAD

**Issue by SirJben** [MiniaturePets/Issues#309]
This issue has been reported by thomaskeig#0001 | 490537526436560896 

[Video](https://streamable.com/qk9opl)

[Spark](https://spark.lucko.me/8TZXUn7bwX)

[Timings](https://timings.aikar.co/?id=18c62de5aef7499a86346f4d1c328f09)

Here's the Discord [Transcript](https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/841740907467636756/976405492425437254/transcript-miniaturepets-0005.html)

**Comment by thomaskeig** [comment]
Any update?

**Comment by Awpmeister2170** [comment]
Hello sorry for the late response here,

No one else has had this issue 🤔 can you try using the most up to date version and seeing if you still lag at all?
