### ISSUE TITLE
[Bug Report] [Important] wall / door bypass

### ISSUE THREAD

**Issue by haroldrc** [MiniaturePets/Issues#310]
# Bug Report

### Technical Information
* Server Software: 
* Plugin Version:  
* Dump File: 
> Use `/mpet dump` to get the dump file.

https://pastebin.com/ZrSPD1av

### General Information

**Bug Description**
when I take a pet it teleports me back 2/3 blocks

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1.  when I take a pet it teleports me back 2/3 blocks

2. 
3. 
4. 

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/).

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.

https://streamable.com/e74qau

**Comment by Awpmeister2170** [comment]
Update to the latest version, that should fix this issue.

**Comment by Awpmeister2170** [comment]
Fixed
