### ISSUE TITLE
[Bug Report] Really important

### ISSUE THREAD

**Issue by Nishibaka** [MiniaturePets/Issues#311]
# Bug Report

### Technical Information
* Server Software: Spigot 1.8.8
* Plugin Version:  LATEST
* Dump File:  https://pastebin.com/dcrCk6Lj
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
i cant use a citizens mpet in 1.8.8. The mob spawn on the NPC and he can move and i can kill him.

![Screenshot_23](https://user-images.githubusercontent.com/104135927/170862915-5aca1646-3c20-4ad1-89d0-3f4fb8fd44c5.png)
![Screenshot_24](https://user-images.githubusercontent.com/104135927/170862951-46aff467-410a-4ee8-b3f5-2ec4f5990903.png)

**Comment by Nishibaka** [comment]
![image](https://user-images.githubusercontent.com/104135927/173880154-e777a956-95e0-4c0f-bbf7-167637b6298e.png)

**Comment by Nishibaka** [comment]
![image](https://user-images.githubusercontent.com/104135927/173880200-30e14874-69b0-437e-bad3-9e5dd5d98a9c.png)

**Comment by Nishibaka** [comment]
![image](https://user-images.githubusercontent.com/104135927/174019911-c6208cfe-078d-4a8b-85f2-f341522ea57c.png)

**Comment by GC-spigot** [comment]
Seems like 1.8.8 is not supported :(
