### ISSUE TITLE
[Feature Request] Hidden players support

### ISSUE THREAD

**Issue by rudde0** [MiniaturePets/Issues#322]
# Feature Request

### General Information

**Feature Description**
Pets should compatible with `player.hidePlayers()` and `player.showPlayers()` functions. Armor stands shouldn't seen by player who can't see the pet owner.

**Visual Demonstration**
Just try to use some vanish plugin or just call hidePlayers() method.

**Comment by rudde0** [comment]
(https://www.spigotmc.org/threads/hiding-an-entity.81669/ is might be helpful)

**Comment by GC-spigot** [comment]
Added
