### ISSUE TITLE
[Bug Report] Pets are hidden from all players if someone hide the player

### ISSUE THREAD

**Issue by rudde0** [MiniaturePets/Issues#326]
# Bug Report

### Technical Information
* Server Software: git-Paper-186 (MC: 1.19.2)
* Plugin Version:  2.7.7

### General Information

**Bug Description**
When someone hide all players from himself all pets are disappearing from all players. And when that player reveal again to all players, pets not spawning again.

**Instructions To Produce**

Pet disappear from all players with no condition:
1. Summon a pet on Player_1
2. Hide all players from Player_2
**Pet hidden for Player_1 and Player_3 too**
(Pet vanished from Player_3 even there is no relation with Player_3)

---
Pet not visible from anyone even player make visible other players again for himself:
1. Reveal all players from Player_2
**No pets visible even pet is selected**

**Comment by GC-spigot** [comment]
Fixed

**Comment by rudde0** [comment]
Pets aren't vanishing anytime right now. Pets are always visible.

**Comment by GC-spigot** [comment]
This is going to be a problem and might stay that way, there’s too many vanish plugins. My honest recommendation is to just remove the pet when vanishing until we figure out a solution. On 2022-10-19, at 10:25 PM, Hazar ***@***.***> wrote:﻿
Pets aren't vanishing anytime right now. Pets are always visible.

**Comment by rudde0** [comment]
May you add simple API to add/remove pet packets from specific player?

**Comment by GC-spigot** [comment]
This doesn’t use packetsOn 2022-10-19, at 10:48 PM, Hazar ***@***.***> wrote:﻿
May you add simple API to add/remove pet packets from specific player?

**Comment by rudde0** [comment]
So isn't there any possible way to prevent pets make vanished from specific players?
