### ISSUE TITLE
[Bug Report] Riding is not working, error.

### ISSUE THREAD

**Issue by Rhbarber** [MiniaturePets/Issues#330]
# Bug Report

### Technical Information
* Server Software: git-Purpur-1862 (MC: 1.19.3)
* Plugin Version:  MiniaturePets_v2.9.0-stable.jar (Plugin showing incorrect version when using /version MiniaturePets)
* Dump File: https://pastebin.com/n1q2wjBn

### General Information

**Bug Description**
Please be as descriptive as possible when describing the bug you are facing, and save no words. Please use a reasonably understandable English, feel free to use stuff like Grammarly to do it.

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
- None, it just randomly happened, the only online player did not use any of the available pets.

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/).
- https://paste.sparked.host/gikopubidu.yaml

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.

**Comment by Awpmeister2170** [comment]
Latest versions should fix this, the plugin has had a huge revamp :)
