### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by Taneax** [MiniaturePets/Issues#338]
# Bug Report

### Technical Information
* Server Software: latest Paper 1.19.3
* Plugin Version:  latest Version
* Dump File: https://pastebin.com/3Y1rBrzh
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Just Error Messages spam in my console every few minutes/seconds the whole day..... every day...

**Instructions To Produce**
https://pastebin.com/BJWVD5h3

**Logs**
https://pastebin.com/BJWVD5h3

**Visual Demonstration**
https://pastebin.com/BJWVD5h3

**Comment by GC-spigot** [comment]
Fixed!
