### ISSUE TITLE
[Bug Report] Default Mini-Me pet no longer functions properly

### ISSUE THREAD

**Issue by SiuanSong** [MiniaturePets/Issues#339]
# Bug Report

### Technical Information
* Server Software: Purpur 1.19.2 #1858
* Plugin Version:  3.0.1
* Dump File: https://pastebin.com/Fywvcw3K
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Mini-Me pet only has a chestplate now, whereas before I know it had the players skull and at least leggings, I don't remember if it had boots.
It is also displayed as a dragon egg in the pet menu, as are many other pets.

**Visual Demonstration**

![javaw_ZgQHgEA9w4](https://user-images.githubusercontent.com/28202890/224201423-cce9f984-317d-410d-bf4c-0a83a91a27e8.png)

![javaw_BXykxvR8gd](https://user-images.githubusercontent.com/28202890/224201447-d83e98ec-9a26-4901-898c-ade97a2936b7.png)

**Comment by sannielollie** [comment]
I can confirm this, having the same issue.
Also having issues with some other old mpets, missing armor and not making movements.
