### ISSUE TITLE
Console error spamming

### ISSUE THREAD

**Issue by abhisantos** [MiniaturePets/Issues#340]
The latest version 3.0.1 is throwing an error in console all day.
Also the version is showing like 2.7.7 and not 3.0.1 when you download it.

The error: 
13.03 10:45:29 [Server] [ERROR] Could not pass event PlayerQuitEvent to MiniaturePets v2.7.7
13.03 10:45:29 [Server] [INFO] java.lang.NullPointerException: Cannot invoke "com.kirelcodes.miniaturepets.pets.Pet.remove(boolean, boolean)" because the return value of "com.kirelcodes.miniaturepets.pets.PetManager.getPet(org.bukkit.entity.Player)" is null
13.03 10:45:29 [Server] [INFO] at com.kirelcodes.miniaturepets.listeners.PlayerQuitListener.playerLeaveEvent(PlayerQuitListener.java:35) ~[MiniaturePets-3.0.1.jar:?]
13.03 10:45:29 [Server] [INFO] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor84.execute(Unknown Source) ~[?:?]
13.03 10:45:29 [Server] [INFO] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
13.03 10:45:29 [Server] [INFO] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-430]
13.03 10:45:29 [Server] [INFO] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
13.03 10:45:29 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-430]
13.03 10:45:29 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-430]
13.03 10:45:29 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
13.03 10:45:29 [Server] [INFO] at net.minecraft.server.players.PlayerList.remove(PlayerList.java:578) ~[paper-1.19.3.jar:git-Paper-430]
13.03 10:45:29 [Server] [INFO] at net.minecraft.server.players.PlayerList.remove(PlayerList.java:563) ~[paper-1.19.3.jar:git-Paper-430]
13.03 10:45:29 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2119) ~[?:?]
13.03 10:45:29 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2098) ~[?:?]
13.03 10:45:29 [Server] [INFO] at net.minecraft.network.Connection.handleDisconnection(Connection.java:777) ~[?:?]
13.03 10:45:29 [Server] [INFO] at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:253) ~[?:?]
13.03 10:45:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[paper-1.19.3.jar:git-Paper-430]
13.03 10:45:29 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-430]
13.03 10:45:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-430]
13.03 10:45:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-430]
13.03 10:45:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-430]
13.03 10:45:29 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by GC-spigot** [comment]
Fixed!
