### ISSUE TITLE
[Bug Report]  Erroring while I am clicking on NPC

### ISSUE THREAD

**Issue by patrikkoudelka** [MiniaturePets/Issues#342]
# Bug Report

### Technical Information
* Server Software: git-Purpur-1927 (MC: 1.19.3)
* Plugin Version:  3.0.1
* Dump File: https://pastebin.com/GU9BkWwV (but I have 3.0.1, idk why it is saying 2.7.7
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Please be as descriptive as possible when describing the bug you are facing, and save no words. Please use a reasonably understandable English, feel free to use stuff like Grammarly to do it.
It gives an error when I try to click on an NPC

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Click to the npc

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/).
https://pastebin.com/3rP9ikPN

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.
I think it is not needed, but let me know

**Comment by GC-spigot** [comment]
Fixed
