### ISSUE TITLE
[Bug Report]  Conflicting with another plugin

### ISSUE THREAD

**Issue by Teddy20002** [MiniaturePets/Issues#345]
# Bug Report

### Technical Information
* Server Software:  1.19.2
* Plugin Version:  3.0.1
* Dump File:  https://pastebin.com/Q5Nc0Nc2
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Console spam

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1.  Download Roulette https://www.spigotmc.org/resources/roulette.82197/   and make a game
2.  click on the table to play (play a few games)
3. Console will get spammed
4. 

**Logs**
https://pastebin.com/tDQhFVYy

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.

**Comment by GC-spigot** [comment]
Fixed!
