### ISSUE TITLE
[Bug Report] Pets are not sorted alphabetically

### ISSUE THREAD

**Issue by SiuanSong** [MiniaturePets/Issues#346]
# Bug Report

### Technical Information
* Server Software: Purpur 1.19.2 #1858
* Plugin Version:  3.0.1
* Dump File: https://pastebin.com/gqxZVk8i
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Pets are not listed alphabetically in the /mpet menu across ALL pages.
In my example below, why aren't all the Cats listed on the same page?  It's like each individual page is alphabetized, but not the entire pets list. It looks really unprofessional and makes things confusing when trying to search for a specific pet.  I've been really wanting to finally set this plugin up on my store, but with how bad the menu looks, I am hesitant to do so.

**Visual Demonstration**

![Page1](https://user-images.githubusercontent.com/28202890/229371058-69984b6a-921f-45ed-97ea-21d841c0eaa0.png)
![Page2](https://user-images.githubusercontent.com/28202890/229371060-68ad1c3b-4fda-4218-b7f8-046f4810e834.png)

**Comment by GC-spigot** [comment]
Resolved! Thank you for reporting

**Comment by SiuanSong** [comment]
This still hasn't been fixed for me.  I did a fresh install of version 3.0.2 and redownloaded the pets.  They are still only alphabetized per page.  I also tested using Paper 1.19.4 #527 and Purpur 1.19.4 #1968 with the same results. I am using the latest dev build of ProtocolLib (#642.)

Dump File: https://pastebin.com/FHEfaBfp
