### ISSUE TITLE
Console spaaaam!

### ISSUE THREAD

**Issue by download042** [MiniaturePets/Issues#347]
# Bug Report

### Technical Information
* Server Software: purpur 1.19.3
* Plugin Version:  2.7.7
* Dump File: https://pastebin.com/4GTspLp6

### General Information

**Bug Description**
Simple console spam at player quit event.

**Instructions To Produce**

1. install mpet
2. join server
3. quit server
4.  voilà

**Logs**
https://pastebin.com/vk8NYMTd

**Comment by GC-spigot** [comment]
Fixed!
