### ISSUE TITLE
[Feature Request] Expand method for API use

### ISSUE THREAD

**Issue by rudde0** [MiniaturePets/Issues#352]
# Feature Request

### General Information

**Feature Description**
I need to access parts variable in CustomEntityInstance for my vanish system. Please consider making parts public or add this method:
```java
    public ArrayList<ArmorStand> getParts() {
        ArrayList<ArmorStand> armorStands = new ArrayList<ArmorStand>();
        for (Map.Entry<String, ArmorStandLocation> entry : this.parts.entrySet()) {
            armorStands.add(entry.getValue().getArmorStand());
        }
        return armorStands;
    }
```

This method will be very helpful for developers who need to access parts of the pet.

**Comment by GC-spigot** [comment]
Added
